### ISSUE TITLE
Plugin site no longer shows active security warnings

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site#102]
Copied from https://issues.jenkins-ci.org/browse/INFRA-2425

https://plugins.jenkins.io/websphere-deployer is a plugin that should show a warning exclamation icon next to the plugin name, that opens a popup listing the active security warnings.

(The warnings in the description text are probably just legacy content from the wiki.)

Additionally, warning indicators appear to have been list on the plugins list (search results etc.) as well, although I'm less sure they existed before.

"Previous security warnings" in the sidebar (e.g. https://plugins.jenkins.io/git ) still exist, so it's unlikely to be a data problem.

cc @daniel-beck / @halkeye

**Comment by timja** [comment]
There's something wrong with the modal code:
https://github.com/jenkins-infra/plugin-site/blob/master/src/components/PluginActiveWarnings.jsx#L23-L45

If I remove the modal code and just have plain html, then the warnings show up (but look horrible)

**Comment by timja** [comment]
With this change I can get the warning icon to show up again, (if I override the display:none for no results)

```
diff --git a/src/styles/base.css b/src/styles/base.css
index 353cd5a..248af53 100644
--- a/src/styles/base.css
+++ b/src/styles/base.css
@@ -237,8 +237,8 @@ transform: scale(-1, 1);
 #pluginPage #grid-box > .content {padding:0 !important; max-height:100% !important; overflow-x: hidden;}
 #pluginPage #grid-box > .content .title {margin-bottom:2rem; vertical-align:top}
 #pluginPage #grid-box > .content .content {min-height:25rem}
-#pluginPage #grid-box > .content .badge-box {display: inline-block;}
-#pluginPage #grid-box > .content .badge-box  > .badge {
+.badge-box {display: inline-block;}
+.badge-box > .badge {
   background: no-repeat top;
   background-size: 3rem;
   display: inline-block;
@@ -250,7 +250,7 @@ transform: scale(-1, 1);
   white-space: nowrap;
   margin: 0 -.5rem 0 .5rem;
 }
-#pluginPage #grid-box > .content .badge-box > .badge.warning {
+.badge-box > .badge.warning {
   background-image: url(../images/warning.svg);
   background-size:2.5rem;
 }
```

But I don't really understand what's going on here with all the gatsby stuff, the modal is broken basically + some css fixes needed.

**Comment by halkeye** [comment]
yea found that too, the .content container must have gotten removed. 

Are you going to PR it? or do you want me to?

**Comment by timja** [comment]
> yea found that too, the .content container must have gotten removed.
> 
> Are you going to PR it? or do you want me to?

better if you do, I wasn't able to get it working.
