### ISSUE TITLE
Favicon images aren't transparent unlike main site

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site#104]
plugin site:
![image](https://user-images.githubusercontent.com/21194782/73026301-11b6df00-3e29-11ea-95c0-9ed46fcb4840.png)

jenkins.io:
![image](https://user-images.githubusercontent.com/21194782/73026280-095ea400-3e29-11ea-963c-edc7d81f5c17.png)

**Comment by zbynek** [comment]
Fixed in #403
