### ISSUE TITLE
Wiki page extraction retrieves wrong wiki page

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#105]
Migrating https://issues.jenkins-ci.org/browse/INFRA-2434:

https://plugins.jenkins.io/external-monitor-job shows the Japanese wiki page content from https://wiki.jenkins.io/display/JA/Monitoring+external+jobs and not the content of https://wiki.jenkins.io/display/JENKINS/Monitoring+external+jobs despite https://github.com/jenkinsci/external-monitor-job-plugin/blob/a401b0ce4220272abd986c85db2aada5de6818fe/pom.xml#L15

**Comment by halkeye** [comment]
That is very very interesting. Its an upstream issue in the plugin api site (which I've copied into the plugin site).

https://plugins.jenkins.io/api/plugin/external-monitor-job has the content as JP so thats what we render.

hrm hrm hrm

**Comment by timja** [comment]
Fixed now:
![image](https://user-images.githubusercontent.com/21194782/73175857-07cffd00-4103-11ea-9383-f207739f040d.png)

May need to clear cache (I had to)

**Comment by daniel-beck** [comment]
Fixed for me as well. Thanks @halkeye
