### ISSUE TITLE
Issues with current Contributing Guide instructions to run the app

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/plugin-site#1125]
Today I was going through the instruction to run the app at https://github.com/jenkins-infra/plugin-site/blob/master/CONTRIBUTING.md#running-the-app. However, I ran into several issues, which require me to do the following to make things work instead:

```shell
yarn install
cd ./plugins/plugin-site
yarn install
yarn dev
```
Then open http://localhost:3000. 

Moreover, I had to manually set the values for `GATSBY_ALGOLIA_APP_ID` and `GATSBY_ALGOLIA_SEARCH_KEY` as environment variable before I could fetch the plugin records. The settings I used were as follows on a Mac:

```shell
export GATSBY_ALGOLIA_APP_ID=HF9WKP9QU1
export GATSBY_ALGOLIA_SEARCH_KEY=4ef9c8513249915cc20e3b32c450abcb
```

Would it be a good idea for me to open a PR to update the run instructions?

**Comment by zbynek** [comment]
I think you shouldn't need the second `yarn install`. Maybe you're using some older version of `yarn`?

As for documenting the Algolia options, it would be great if you would add it (there's a ticket for it https://github.com/jenkins-infra/plugin-site/issues/631 )

**Comment by krisstern** [comment]
Hi @zbynek Yes, I am using the classic version of `yarn`. Must be why.

Also, I would follow up on documenting the Algolia options and open a PR for the ticket #631 soon.

**Comment by zbynek** [comment]
@krisstern OK to close this issue?

**Comment by krisstern** [comment]
Yup
