### ISSUE TITLE
Link from each plugin page to the extension point list

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkins-infra/plugin-site#1131]
### Service(s)

plugins.jenkins.io

### Summary

Please add a link from each plugin page to the list of extension points defined in that plugin. For example, link from <https://plugins.jenkins.io/junit/> to <https://www.jenkins.io/doc/developer/extensions/junit/>. The new link could go between the "Pipeline Step Reference" and "Javadoc" links.

**Comment by halkeye** [comment]
Huh that extension page needs some mobile love

Can you describe your usecase a bit more? I don't see any issues getting it done but more context is always more better for whomever takes the feature request

**Comment by KalleOlaviNiemitalo** [comment]
I was looking at [JENKINS-63368](https://issues.jenkins.io/browse/JENKINS-63368) and wanted to check which plugins provide test result storage for junit-plugin. I had visited [Extension Index](https://www.jenkins.io/doc/developer/extensions/) earlier so I was able to reopen that page from the Web browser history and follow the [Extension points defined in JUnit Plugin](https://www.jenkins.io/doc/developer/extensions/junit) link from there. This is however not so easy if the page is not in the history; from the jenkins.io front page, it is not obvious that one has to navigate to Documentation - Developer Guide - Extensions Index. If the link had existed, I'd have been able to take the "junit-plugin" component name from Jira and guess "https://plugins.jenkins.io/junit" and follow the link from there. And it would have much the same user audience as the javadoc link that already exists.

**Comment by AgnelFernando** [comment]
Hi @halkeye Can I take this one?
And there is any way to find plugin have extensions? Like `plugin.hasPipelineSteps`

**Comment by halkeye** [comment]
You absolutely can take this.

Right now I don't know how to tell if a plugin has pipeline steps. Maybe @kwhetstone or @vihaanthora can provide insight

**Comment by zbynek** [comment]
@gilesagnel the pipeline reference on jenkins.io exports its content to `contents.json` via https://github.com/jenkins-infra/jenkins.io/pull/4334 , that's consumed by plugin-site (to set the `plugin.hasPipelineSteps` flag you mentioned). Similar approach should work for extension list -- you can file one PR for jenkins.io, one for plugin-site. 

One could also cut the middle-man and download the zip directly by plugin-site, similar to https://github.com/jenkins-infra/jenkins.io/blob/master/scripts/fetch-external-resources#L60 but I think it's better to keep as few dependencies on ci.jenkins.io as possible.

**Comment by AgnelFernando** [comment]
Thank you @zbynek Thats help.

**Comment by KalleOlaviNiemitalo** [comment]
Wow, there is now an "[Extension Points](https://www.jenkins.io/doc/developer/extensions/junit)" link at <https://plugins.jenkins.io/junit/>. Thank you, @gilesagnel.
