### ISSUE TITLE
Add a darkmode

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1146]
Currently, https://plugins.jenkins.io/ has no dark mode at all. It would be pretty awesome, if we would have a darkmode switch on the page, allowing the user to toggle the theme or rely on the system theme and switch automatically.

**Comment by zbynek** [comment]
I guess the main prerequisite for  this is to create a dark mode for the website (jenkins.io and plugins.jenkins.io). Maybe a good hacktoberfest project?

**Comment by NotMyFault** [comment]
> I guess the main prerequisite for this is to create a dark mode for the website (jenkins.io and plugins.jenkins.io). Maybe a good hacktoberfest project?

To be fair, we don't have any dark mode at all yet. That's just darkreader doing its thing, but it would be nice to have I guess? At least for plugins.jenkins.io

Not too sure about the scope, but plugins.j.io _may_ seem straightforward, given it's just rendered markdown (mostly)

**Comment by jmMeessen** [comment]
Hello @zbynek (and @NotMyFault )

I am going to mention the dark mode for plugins.jenkins.io in the public Hacktoberfest documentation. We'll see if anyone picks up the bait. 
Depending on how much attention we want to draw on it, we can label this issue as "hacktoberfest".

**Comment by SumitVerma-coder** [comment]
**_Please assign me this issue under HACTOBERFEST tag_**

**Comment by halkeye** [comment]
the comment here is good enough to say you are working on it. We've had issues assigning tickets during hacktoberfest and nobody returning in the past.

We'll add the hacktoberfest label to the PR so you get credit for it.
