### ISSUE TITLE
Weird "Report a problem" behavior on plugin site

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1199]
Plugin pages on plugins.jenkins.io have a link labeled "Report a problem" in the footer.

Usually on jenkins.io it is a content problem, but this one links to the plugin's issue tracker as a redundant link for reporting a bug (the main links are in the sidepanel).

Yet the link has a title/tooltip indicating it's for a content bug on the page:
> <img width="421" alt="Screenshot 2022-05-09 at 21 58 37" src="https://user-images.githubusercontent.com/1831569/167487834-fca350cf-b4f9-495f-93a0-6bfac6344eaf.png">

All of this is very confusing and the link should probably just be gone.

**Comment by halkeye** [comment]
Yea I wasn't a fan of it when it was installed, Its probably more useful to link to the github repo now that most docs come from there. But we also have it linked so many other places, i'm not sure its useful at all.

**Comment by daniel-beck** [comment]
I mean, https://plugins.jenkins.io/lolwut links to https://github.com/jenkins-infra/plugin-site/issues/new?labels=bug&template=4-bug.md&title=Plugin%20page%20not%20found%20page%20-%20TODO:%20Put%20a%20summary%20here&body=Problem%20with%20the%20[Plugin%20page%20not%20found](https://plugins.jenkins.io)%20page,%20[source%20file](https://github.com/jenkins-infra/plugin-site/tree/master/src/pages/404.jsx)%0A%0ATODO:%20Describe%20the%20expected%20and%20actual%20behavior%20here%20%0A%0A%23%23%20Screenshots%20%0A%0A%20TODO:%20Add%20screenshots%20if%20possible%20%0A%0A%23%23%20Possible%20Solution%20%0A%0A%3C!--%20If%20you%20have%20suggestions%20on%20a%20fix%20for%20the%20bug,%20please%20describe%20it%20here.%20--%3E%20%0A%0AN/A which looks kinda sane (if a bit pointless for generated pages). The main problem IMO is the unexpected override with the other bug report functionality.
