### ISSUE TITLE
HCL AppScan Jenkins plugin stop working after upgrade from SAClientUtil.8.0.1480  to SAClientUtil.8.0.1498

### ISSUE THREAD

**Issue by amarm85** [jenkins-infra/plugin-site#1206]
Problem with the [HCL AppScan](https://plugins.jenkins.io/appscan) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

My Jenkins pipeline was working fine until today. I see the log says below message  

```
[Pipeline] stage
[Pipeline] { (appscan)
[Pipeline] appscan
A newer version of the SAClientUtil package is available:
Current Version: 8.0.1480
Available Version: 8.0.1498
Downloading the latest SAClientUtil package...
Download complete.
Extracting the SAClientUtil package...
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Failed to run the security scan: The security analysis process failed. 

/home/jenkins/.appscan/SAClientUtil.8.0.1498/jre/lib/server/classes.jsa (No such file or directory)
```

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by halkeye** [comment]
So this issue tracker is for the plugin site itself, not issues with plugins. Sadly this plugin doesn't have any issue tracker enabled.

As this is a 3rd party plugin created by a 3rd party I would recommend reaching out to them, and either indicating how to report issues in the readme, or enabling one of the jenkins provided ones in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-appscan.yml
