### ISSUE TITLE
Mina SSHD API Version 2.8.0-30.vf9df64641cb_d  created a circular dependency

### ISSUE THREAD

**Issue by sarg3nt** [jenkins-infra/plugin-site#1213]
Problem with the [Mina SSHD API :: Core](https://plugins.jenkins.io/mina-sshd-api-core) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

When we upgraded to the 2.8.0-30.vf9df64641cb_d version of this plugin it created a circular dependency error.
`Cycle detected: Plugin:sshd -> Plugin:mina-sshd-api-core -> Plugin:ssh-credentials -> Plugin:credentials -> Plugin:configuration-as-code -> Plugin:commons-text-api -> Plugin:commons-lang3-api -> Plugin:sshd`

This caused many other plugins to disable 
When we downgrade this plugin to 2.8.0-21.v493b_6b_db_22c6 the problem was fixed.
The problem was probably introduced with this added feature:
Add optional SSHAuthenticator implementation ([#13](https://github.com/jenkinsci/mina-sshd-api-plugin/issues/13)) [@Dohbedoh](https://github.com/Dohbedoh)
https://issues.jenkins.io/browse/JENKINS-64105

I can provide our complete list of installed plugins if that helps.  We deploy Jenkins as Docker containers on Kubernetes clusters using Terraform so providing config is no problem.

## Screenshots 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/3372486/179630780-f0cdb9ef-2d58-4113-9526-4e93ab823a0e.png">

**Comment by halkeye** [comment]
Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself.

> https://issues.jenkins.io/browse/JENKINS-69034 provides the background and a work around. Essentially Downgrade the two mina plugins.

In the future please use the [forum](https://community.jenkins.io/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)

**Comment by sarg3nt** [comment]
Oops, sorry.
