### ISSUE TITLE
Releases show time always as midnight while appearing to have higher resolution than "day"

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1220]
Plugin site right now:
> <img width="720" alt="Screenshot 2022-08-11 at 21 41 33" src="https://user-images.githubusercontent.com/1831569/184225558-f2dd1e06-1b18-4302-bbf7-802d836648aa.png">

Jenkins right now:
> <img width="470" alt="Screenshot 2022-08-11 at 21 41 39" src="https://user-images.githubusercontent.com/1831569/184225576-299b1367-20ea-4c64-b235-feeb063955d4.png">

I was genuinely wondering whether that's the same release until I noticed that the tooltip on the plugin site says the release was at 00:00.

Unsure what the data source is, but if it only has day resolution, the human-friendly labels should just say "today", "yesterday", "X days ago" instead of "X hours ago", and the tooltip shouldn't give the time.

**Comment by zbynek** [comment]
It's using https://updates.jenkins.io/current/plugin-versions.json -- is there some other source with higher date resolution?

**Comment by daniel-beck** [comment]
Not yet, but I'm working on update-center2 right now anyway, so I can add that.

**Comment by daniel-beck** [comment]
https://github.com/jenkins-infra/update-center2/pull/636 would add a better timestamp to `plugin-versions.json`.

**Comment by zbynek** [comment]
@daniel-beck the proposed PR looks good, if you can merge it I can implement the fix in `plugin-site`.

**Comment by daniel-beck** [comment]
> <img width="355" alt="Screenshot 2022-08-31 at 22 44 08" src="https://user-images.githubusercontent.com/1831569/187778428-e72c2f08-277c-494a-a043-4137393435dc.png">

> <img width="1478" alt="Screenshot 2022-08-31 at 22 45 44" src="https://user-images.githubusercontent.com/1831569/187778723-3794b204-fbfd-43c4-b7f5-52b5d7fcedab.png">


🎉 Thanks @zbynek & @halkeye !
