### ISSUE TITLE
Replace install count with install percentage

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1238]
Install count does not generally mean anything to users as a popularity indicator unless they know what the most popular plugin is (as a benchmark for comparison) or the total install count from the stats site.

Additionally, the number of instances reporting data seems to fluctuate a bit from month to month. Whether as an artifact to stats collection or because Jenkins becomes genuinely more (or less) popular, that shouldn't affect plugin popularity -- but right now it does: A lot of plugins jumped in popularity from Feb to March this year, e.g. `matrix-auth` ~7%! In reality, as a percentage, `matrix-auth` even dropped a bit from 94.6% to 94.2%.

It would seem more useful to show install percentage.

One potential challenge with this would be that we shouldn't show raw floats/doubles with way too many digits, and 1% translates to roughly 3000 installs. To make this feasible for the long tail of plugins with less than 1% install count, there should always be two significant digits shown for install percentage:

https://plugins.jenkins.io/matrix-auth/ - 93%
https://plugins.jenkins.io/blueocean/ - 22%
https://plugins.jenkins.io/groovy/ - 9.8%
https://plugins.jenkins.io/strict-crumb-issuer/ - 2% (rounded from 2.0074%)
https://plugins.jenkins.io/solarized-theme/ - 0.36%
https://plugins.jenkins.io/generic-environment-filters/ - 0.012%
https://plugins.jenkins.io/csp/ - 0.0065%

The detailed tooltips on the graph should continue to show absolute numbers (as well as percentage), so users aren't confused why "98%" on every month isn't an exactly straight line, but the top-level label is probably better as percentage only.

Thoughts?

**Comment by zbynek** [comment]
The only potential downside is that "1700 installs" sounds more trustworthy than 0.36%. Maybe the absolute number could be shown in tooltip?

**Comment by daniel-beck** [comment]
> Maybe the absolute number could be shown in tooltip?

Agree. That's what I meant by

> The detailed tooltips on the graph should continue to show absolute numbers
