### ISSUE TITLE
Layout issues on "Releases" tab on page load

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-site#1240]
When opening a plugin release page (or when refreshing it), the layout is broken until there is a tab change.

Reproduction steps:
- Go directly to https://plugins.jenkins.io/ec2/#releases

- Notice how the first release borders are missing, and how the GitHub icon is too close to the release title:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/91831478/189628142-8232c722-fdf4-4715-8798-06c00fcbc2b9.png">

- Click on "Documentation", "Issue" or "Dependencies" tab then come back to the "Releases" tab

- Notice how the layout has been corrected:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/91831478/189627527-db3352ae-f85b-4e15-8b60-ec78ee147c4c.png">

Expected: correct layout on page load.

I suppose it's a JavaScript event issue.

**Comment by halkeye** [comment]
the `class=card-text` gets replaced with `<div id="plugin-content-readme" class="md" data-path="README.md">` and I can't figure out why. We must be pulling in some javascript somewhere there is doing it

**Comment by halkeye** [comment]
oh, plugin-content is on rehype stuff, that is the main documentation body payload. I wonder if its a gatsby bug

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/plugin-site/pull/1295
