### ISSUE TITLE
Plugins page - Plugin documentation and versions doesn't get updates

### ISSUE THREAD

**Issue by curveenk** [jenkins-infra/plugin-site#1243]
We observed that our plugin page is not getting updated for 2 latest release(s) starting from last week:
https://plugins.jenkins.io/eggplant-runner/
- The documentation changes does not reflect
- Plugin version is not updated

The two versions (0.0.1.191.v72dea_07931b_6 and 0.0.1.189.v1e3397db_cee8) are already available for install for users but the page isn't in sync with the latest updates, it is still showing 0.0.1.185.v9617008ee458.
https://github.com/jenkinsci/eggplant-runner-plugin/releases/tag/0.0.1.191.v72dea_07931b_6
https://github.com/jenkinsci/eggplant-runner-plugin/releases/tag/0.0.1.189.v1e3397db_cee8

Could you help to advise what could be wrong and where else should we check for the status for page update?

Thanks in advance!

Problem with the [Plugins Index](https://plugins.jenkins.io) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/index.jsx)

## Screenshots
![image](https://user-images.githubusercontent.com/103989779/196146017-3c648675-d7b2-42be-b103-9aea7acd6bff.png)

## Possible Solution

Perhaps something have to be refreshed?

**Comment by lemeurherve** [comment]
Closing in favor of [the issue you've previously opened in the help desk](https://github.com/jenkins-infra/helpdesk/issues/3181).
