### ISSUE TITLE
Display artifact id on plugin page

### ISSUE THREAD

**Issue by olivergondza** [jenkins-infra/plugin-site#1260]
Moved from https://issues.jenkins.io/browse/WEBSITE-795

Some plugin have vastly different name and artifactId. This can be confusing for users of containerized jenkins / plugin install tool. I am aware this is disclosed once clicking on "How to install", though I still find this hard to find. After all, the problem is not users would not know how to install plugins, they are surprised by the id being different.

Present the artifactId on the page itself.

**Comment by NotMyFault** [comment]
+1

Currently, the artifactId is only displayed if a plugin is suspended.
