### ISSUE TITLE
Plugin distribution has been suspended, see https://www.jenkins.io/security/plugins/#suspensions for details.

### ISSUE THREAD

**Issue by sitaorg2022** [jenkins-infra/plugin-site#1263]
I am trying to configure the kube credential in jenkins . I guess I need to install kubernetes-cd plugin from "https://plugins.jenkins.io/kubernetes-cd/" . But I am getting the message as 
 "Plugin distribution has been suspended, see https://www.jenkins.io/security/plugins/#suspensions for details." So what is the alternative plugin for kubernetes-cd. I am looking for one to Configuring Kubernetes Credentials On Jenkins Server

![image](https://user-images.githubusercontent.com/114043988/215047117-c2f17e3a-62ab-41ea-8044-92d9958aac28.png)

**Comment by halkeye** [comment]
This is not a bug with plugin site. 

Your options will depend on the notice. there might not be an alternative until someone steps up to fix it
