### ISSUE TITLE
Basic Branch Build Strategies | Jenkins plugin page - update outdated link

### ISSUE THREAD

**Issue by apollo7321** [jenkins-infra/plugin-site#1266]
Problem with the [Basic Branch Build Strategies | Jenkins plugin](https://plugins.jenkins.io/basic-branch-build-strategies/) page

Outdated link to docs

# Possible Solution

Replace `https://github.com/jenkins-infra/plugins-wiki-docs/blob/master/basic-branch-build-strategies/README.md` by `https://github.com/jenkinsci/basic-branch-build-strategies-plugin/blob/master/docs/user.adoc` on https://plugins.jenkins.io/basic-branch-build-strategies/

**Comment by halkeye** [comment]
https://github.com/jenkinsci/basic-branch-build-strategies-plugin/blob/master/pom.xml#L44 needs to be updated (i think it is) then a release needs to happen (I don't think its happened). I'm not sure there's any actual maintainer to do that though.

We generally don't hack in on the plugin site unless the plugin can't be released. I'm going to close this
