### ISSUE TITLE
Feature Request: be able to jump directly on a specific plugin release via an anchor

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-site#1273]
Currently there is no way to get a link pointing directly to a specific release.

Having something like an anchor on the release date for example would be really nice.

**Comment by Harsh3341** [comment]
Could you tell me more about where this should be added?

**Comment by halkeye** [comment]
Its going to take a bit decent amount of rework to get this working. We already use anchors to switch between tabs, which is breaking https://github.com/jenkins-infra/plugin-site/issues/1240

To be fixed properly, the tabs should be seperate rendered pages (p.j.io/$pluginName/releases) then it should be pretty straight forward to have anchors to releases (p.j.io/$pluginName/releases#v1.2.3.4)

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/plugin-site/pull/1295

**Comment by halkeye** [comment]
I'm going to leave this open because it could still use an icon, but you can now link directly to releases.

**Comment by hervelemeur** [comment]
Thanks @zbynek!
