### ISSUE TITLE
AWS Parameter Store Build Wrapper | Jenkins plugin page - TODO: Put a summary here

### ISSUE THREAD

**Issue by sivasankartest** [jenkins-infra/plugin-site#1282]
Problem with the [AWS Parameter Store Build Wrapper | Jenkins plugin](https://plugins.jenkins.io/aws-parameter-store) page

use case:
Performed below list as part of integration of AWS parameter store with jenkins.
1)AWS Parameter store build wrapper plugin installed on jenkins running on aws ec2 instance
2)Attached IAM Role with SSM policy(parameter store comes under) to the jenkins aws ec2 instance
3)created secret credentials to communicate with aws account on the jenkins
4)created one of the parameter with values and trying to retrieve the value from jenkins via pipeline as well freestyle jenkins job
5)jenkins is unable to make api calls to aws account 
Note: able to make a call via aws cli and retrieve the values

# Screenshots
![pipeline](https://user-images.githubusercontent.com/24208505/217879445-4c731ab3-08f0-489c-8a66-f5d9d983aa0f.jpeg)
![pipeline-job-console-output](https://user-images.githubusercontent.com/24208505/217879462-36c986f4-a6fc-42db-98d4-0fd7981fb7dc.jpeg)

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/), [community forum](https://community.jenkins.io) or the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
