### ISSUE TITLE
Optimize scaling of plugin installation trends

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#129]
In some cases trends look and feel can be improved, especially we could chose minimum and maximum Y axis values. See the trend for Ownership plugin, for example

![image](https://user-images.githubusercontent.com/3000480/74663952-11e29a00-519d-11ea-9d15-f4f4e9d2556d.png)

**Comment by ARUNMOHANRAJ471** [comment]
Hi @oleg-nenashev , I would like to take up this issue. Could you pls assign this to me.

**Comment by halkeye** [comment]
Its yours now

**Comment by zbynek** [comment]
@oleg-nenashev @ARUNMOHANRAJ471 would it make sense to convert the graph into a sparkline? (so basically remove the labels and make it smaller)
https://whawker.github.io/react-jsx-highcharts/examples/Sparkline/index.html has some nice demo of sparklines using a different NPM package. Together with the total number of installs this should convey the same information without taking up so much space.

**Comment by zbynek** [comment]
Fixed in #402 and #445 , further improvements in progress in #447.
