### ISSUE TITLE
LDAP | Jenkins plugin page - Test LDAP Settings throws an exception

### ISSUE THREAD

**Issue by garyavery** [jenkins-infra/plugin-site#1290]
Problem with the [LDAP | Jenkins plugin](https://plugins.jenkins.io/ldap/#issues) page

Jenkins LDAP security realm is correctly configured to use JumpCloud for LDAP authentication.
(see https://support.jumpcloud.com/support/s/article/configuring-jenkins-to-use-jumpclouds-ldap-as-a-service1)

Click on Test LDAP Settings, enter username and password and then click on Test button (see screenshot).
Modal window disappears and there is no indication of what happened.
Expected to see status lines showing the attempted connection to JumpCloud and authentication results.
Have had this configuration in place for over 5 years without any changes.
Successfully authenticates to JumpCloud on Jenkins login without issue.
Test LDAP settings used to work on Jenkins 2.332.2 but not since I upgraded to Jenkins 2.375.3.

jenkins.err.log shows the following exception was thrown:
2023-02-23 23:25:53.154+0000 [id=18]	WARNING	o.e.j.s.h.ContextHandler$Context#log: Error while serving http://jenkins.edgeconnex.com:8080/manage/descriptorByName/hudson.security.LDAPSecurityRealm/validate
java.lang.NullPointerException: Cannot invoke "hudson.security.LDAPSecurityRealm.getConfigurations()" because "realm" is null
	at hudson.security.LDAPSecurityRealm$DescriptorImpl.validate(LDAPSecurityRealm.java:1596)
	at hudson.security.LDAPSecurityRealm$DescriptorImpl.doValidate(LDAPSecurityRealm.java:1551)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)

# Screenshots

![Screen Shot 2023-02-23 at 6 39 31 PM](https://user-images.githubusercontent.com/60115334/221056052-e5268651-cfa9-4571-af0d-1ecc85c3faea.png)

# Possible Solution

N/A

**Comment by NotMyFault** [comment]
This repository is for issues with the website plugins.jenkins.io, not for issues with plugins itself.

Please report issues with plugins to the plugin issue tracker. You can find the link on plugins.jenkins.io.

Edit: Looks like I can't close issues here 👀
