### ISSUE TITLE
Jenkins Plugins page - Link is Broken

### ISSUE THREAD

**Issue by heysujal** [jenkins-infra/plugin-site#1313]
Problem with the [Jenkins Plugins](https://plugins.jenkins.io/) page[source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/index.jsx)
TODO: This link is broken both in the "improve this page" and "report this page" links.

**Comment by zbynek** [comment]
which link?

**Comment by lemeurherve** [comment]
I think this one: `https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/index.jsx?rgh-link-date=2023-03-13T09%3A15%3A29Z`

The `/plugins/plugin-site/` part is missing: `https://github.com/jenkins-infra/plugin-site/blob/master/plugins/plugin-site/src/templates/index.jsx`, both in the "improve this page" and "report this page" links.

If it's the case, this issue concerns https://github.com/jenkins-infra/jenkins-io-components, cc @NotMyFault @halkeye
