### ISSUE TITLE
Update issue link in footer via `reportAProblemTemplate`

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1317]
I noticed you copied my issue template from jenkins.io in https://github.com/jenkins-infra/plugin-site/commit/ad56209fd22fb5dce1c5d63e96817ad03cc9e564.

We could make use of `reportAProblemTemplate` and specify the template added.

**Comment by kanhadharmikk** [comment]
I want to work on this issue.

**Comment by zbynek** [comment]
@NotMyFault the footer link is using the same template name for all domains, so maybe we can just keep the name as it is?

It might make sense to add extra fields to the template in this repo though (as indicated in https://github.com/jenkins-infra/plugin-site/issues/1318#issuecomment-1478530722). Do you want to work on this?

**Comment by NotMyFault** [comment]
> the footer link is using the same template name for all domains, so maybe we can just keep the name as it is?

The current link points to https://github.com/jenkins-infra/plugin-site/issues/new?labels=bug&template=4-bug.md, while there's no such template. The template in this repository is named 4-bug.yml
