### ISSUE TITLE
Links to filter by maintainers are broken

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1318]
### Problem with this page

any search result page

### Expected behavior

Search results are filtered by the maintainer I click on

### Actual behavior

They're not

**Comment by daniel-beck** [comment]
Weird template. There was nowhere to put steps to reproduce, so I didn't :trollface:

**Comment by zbynek** [comment]
Wondering if they ever worked from the search page (they are OK on the plugin pages). Looks like `stopPropagation` is needed when nesting links in links, same problem with the tags.
