### ISSUE TITLE
Algolia API Key is exposed in the headers 

### ISSUE THREAD

**Issue by Mahmoudgalalz** [jenkins-infra/plugin-site#1325]
### Problem with this page

https://plugins.jenkins.io/ui/search/?sort=relevance&categories=&labels=&view=List&page=4&query=

### Expected behavior

The API key should be sent with headers, or be encrypted 

I don't know how the request is sent, but I will investigate 

### Actual behavior

we should send the API key encrypted within the headers

**Comment by halkeye** [comment]
> we should send the API key encrypted within the headers

no its public information, its a read only token talking to algolia

**Comment by halkeye** [comment]
you can read a bit more at https://www.algolia.com/doc/guides/security/api-keys/

**Comment by halkeye** [comment]
ps, I do appreciate the bug report, but we've had debates with this and sentry keys a few times, every time someones automated scanner picks it up, so I wanted to shut down the discussion asap.

**Comment by Mahmoudgalalz** [comment]
I got that, is okay to by a public key, I'm sorry

Thanks @halkeye
