### ISSUE TITLE
Plugin health scores not useful

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1328]
### Problem with this page

https://plugins.jenkins.io/ui/search?sort=relevance&labels=&view=Tiles&page=1&query=

### Expected behavior

Provide explanations or references about the health scores that are useful to maintainers and users.

### Actual behavior

The linked page displays plugin health scores without any explanations. As a plugin maintainer who wants to learn more it's a dead end.

Additionally, the health scores are shown too prominently IMO compared to other plugin metadata, but I guess that's subjective.

**Comment by Harsh3341** [comment]
Hey @daniel-beck there are further works to be done about the explanation of how healthcare is being calculated and why that particular plugin has that score 
https://github.com/jenkins-infra/plugin-site/pull/1320#issuecomment-1500861157
As mentioned previously, I'm gonna raise a PR soon for this issue

**Comment by Harsh3341** [comment]
> Expected behavior
Provide explanations or references about the health scores that are useful to maintainers and users.

@halkeye is there anything else we can do for this particular issue? we can close this issue as PR #1331 solve this

**Comment by halkeye** [comment]
well the comment was that the UI doesn't have really enough context or info.

I'm not sure we really fixed that at all.

**Comment by halkeye** [comment]
oh maybe we did. What do you think @daniel-beck ?

**Comment by daniel-beck** [comment]
Thanks for adding the link!

The health score page has the same problem (light on details, explanations, etc.) but that's a different component.

**Comment by Harsh3341** [comment]
Ya, there is still not much detail about the plugin (which will be done after adding a separate component) but for this particular issue, a reference is been added to solve it.
for details, we can solve it in #1329

**Comment by alecharp** [comment]
@daniel-beck please let me know on https://github.com/jenkins-infra/plugin-health-scoring how we can improve the information there. My guess is that we might have the same problem on #1329.
