### ISSUE TITLE
Plugin health scores not shown on individual plugin pages

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1329]
### Problem with this page

https://plugins.jenkins.io/matrix-auth/ (etc.)

### Expected behavior

Health score (same as on the lists pages) is shown.

### Actual behavior

Health score is not shown.

### Possible solution

Individual plugin pages are a far more common landing page (e.g. from Jenkins directly) than search.

**Comment by Harsh3341** [comment]
https://github.com/jenkins-infra/plugin-site/issues/1328#issuecomment-1503249926
This idea of displaying plugin health scores for the individual plugin on a separate page was included in the GSoC 2023 idea and will implement in follow up PR's

**Comment by alecharp** [comment]
I'm starting to work on this. Can someone assign this issue to me? Thanks. cc @halkeye

**Comment by Harsh3341** [comment]
> I'm starting to work on this. Can someone assign this issue to me? Thanks. cc @halkeye

Can I help you with it? My exams are ending tomorrow

**Comment by alecharp** [comment]
@daniel-beck when you have some time, I'd love to get your feedback on the current status of #1431. There is a screenshot of the current state of the page in the pull request description.

**Comment by daniel-beck** [comment]
@alecharp Screenshot looks nice 👍
