### ISSUE TITLE
Unwanted Spacing

### ISSUE THREAD

**Issue by Harsh3341** [jenkins-infra/plugin-site#1338]
### Current View

![bug](https://user-images.githubusercontent.com/101264150/233177363-5f0294fa-688e-49c9-874c-ee840624d6bf.PNG)

Unwanted spacing below the navbar

### Expected View

![bug-fix](https://user-images.githubusercontent.com/101264150/233178780-7c20569e-2c54-4eb6-b77c-7a3a1607a0b6.PNG)

**Comment by halkeye** [comment]
oh its probably related to #1322 which updated @jenkinsci/gatsby-plugin-jenkins-layout
but i'm not sure the class got updated properly.

**Comment by zbynek** [comment]
This can be fixed by merging https://github.com/jenkins-infra/jenkins.io/pull/6218 -- the class change in layout lib was based on new CSS for jenkins.io which got reverted.
