### ISSUE TITLE
Add a plugin tag cloud to the front page and search windows

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#137]
It would be cool if we could use labels to generate a tag cloud. It would help to highlight the most popular areas/technologies and help users to discover them.

Nice 2 have: each label is a hyperlink

![image](https://user-images.githubusercontent.com/3000480/75437540-a47df880-5956-11ea-9b97-cb922fe02ed3.png)

**Comment by tkelley-eg** [comment]
I spent just a little time on this and it seems this component would be nice:

https://github.com/madox2/react-tagcloud

This query should do the trick and can be reduced down to the data structure required by the component:

```javascript
query MyQuery {
  allJenkinsPlugin {
    nodes {
      labels
    }
  }
}
```
I hope to take a crack at the javascript code to translate the structure sometime this week.

**Comment by daniel-beck** [comment]
Given what the actual tags that are used most often seem to be per the linked PR, I seriously doubt this would be all that useful. We're not highlighting all the cool technologies you can use with Jenkins, but mostly expose the exciting categories of "builder", "notifier", "external", "post-build", "report", and "misc".

Highlighting how popular the tags "adopt-this-plugin" and "deprecated" are is also not quite front page material.

**Comment by oleg-nenashev** [comment]
We could filter out the tags we do not want there

**Comment by tkelley-eg** [comment]
> Given what the actual tags that are used most often seem to be per the linked PR, I seriously doubt this would be all that useful. We're not highlighting all the cool technologies you can use with Jenkins, but mostly expose the exciting categories of "builder", "notifier", "external", "post-build", "report", and "misc".
> 
> Highlighting how popular the tags "adopt-this-plugin" and "deprecated" are is also not quite front page material.

It seems valuable that we've actually been able to see what the cloud looks like so there can be some debate on whether the information is useful or not.  I'm not sure what process you all might use to determine if this is a worthwhile feature for the front page or anywhere else in the app?  I'm happy to invest more time to complete this, but only if it's seems valuable enough to get merged :-)

It's not a problem to add an `block` list to prevent some less useful labels from appearing.  It would seem reasonable that the new react component could just store that locally.

cc: @halkeye @zbynek

**Comment by halkeye** [comment]
> Highlighting how popular the tags "adopt-this-plugin" and "deprecated" are is also not quite front page material.

yea lets hide those tags. Once we get rid of the hard to read colors, i'm happy to merge it, and then revisit

**Comment by tkelley-eg** [comment]
> > Highlighting how popular the tags "adopt-this-plugin" and "deprecated" are is also not quite front page material.
> 
> yea lets hide those tags. Once we get rid of the hard to read colors, i'm happy to merge it, and then revisit

ok, sweet.  When someone has a moment, can I have a list of specific tags we want to hide?

**Comment by halkeye** [comment]
https://plugins.jenkins.io/api/labels
"adopt-this-plugin"
"deprecated"
"must-be-labeled"
"plugin-test"

There's def some not useful (ex "file", "website") tags in the full list, but they'll be okay now, and hopefully encourage people to tag their repos

**Comment by tkelley-eg** [comment]
Here are some color options, which are considerably darker than my first (default) attempt:


`{luminosity: 'dark',format: 'rgba',alpha: 1.0}`

![image](https://user-images.githubusercontent.com/3812023/96526488-b09f2900-124b-11eb-9751-5bde941e3a67.png)


`{luminosity: 'dark',format: 'rgb'}`

![image](https://user-images.githubusercontent.com/3812023/96526426-7b92d680-124b-11eb-8df1-af41c026371b.png)

**Comment by halkeye** [comment]
Can I defer to @zbynek? 

I like the second one better except the yellow on white is hard for me to read.

**Comment by tkelley-eg** [comment]
If anybody wants to play with some colors - https://randomcolor.lllllllllllllllll.com/

**Comment by RiyaGupta89** [comment]
@zbynek Is this issue still open and can I work on this issue?

**Comment by zbynek** [comment]
@RiyaGupta89 I don't think there is enough consensus on how/whether this should be implemented. 
@oleg-nenashev I'm closing this for now, if you want this implemented let's discuss the goals first.
