### ISSUE TITLE
Add a "Report a problem" button to the footer

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#138]
it would be great to add a new "report a problem" button so that Jenkins users could quickly create GitHub issues. It would be similar to what @timja did in https://github.com/jenkins-infra/jenkins.io/pull/2896 for jenkins.io

**Comment by apavlidi** [comment]
Hello @oleg-nenashev 

I tried to add it, but couldn't find the file that generates the **\<footer\>** tag. Is it even on this project or it pulled from an external source? 

Thanks :call_me_hand:

**Comment by halkeye** [comment]
so https://github.com/jenkins-infra/plugin-site/blob/master/utils.js generates/copies all the jenkins.io html to the plugin site. I wouldn't try to modify that at all.

https://github.com/jenkins-infra/plugin-site/blob/master/src/templates/plugin.jsx is the specific plugin page, and probably is the best place to start.

**Comment by GuelorEmanuel** [comment]
@oleg-nenashev I think I have a quick solution for this. Can you assign this to me, as long as it's ok with @apavlidi?

**Comment by oleg-nenashev** [comment]
Thanks for your contribution @GuelorEmanuel !
