### ISSUE TITLE
Site crashes when plugin has no HealthScore

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/plugin-site#1393]
### Problem with this page

https://plugins.jenkins.io/ui/search?query=cdevents

### Expected behavior

We should be able to see the card of the plugin CDEvents.

### Actual behavior

The plugin `CDEvents` is a rather recent addition to the ecosystem. Because of this, the plugin has no score yet (working on this aspect). Because of this, the app crashed.
This is reproducible locally.

**Comment by alecharp** [comment]
This was reported here https://github.com/jenkins-infra/helpdesk/issues/3547

**Comment by alecharp** [comment]
@Harsh3341 I think we need to hide the `PluginHealthScore` for such cases.

**Comment by Harsh3341** [comment]
> @Harsh3341 I think we need to hide the `PluginHealthScore` for such cases.

ya should I display the value as 0 and mention the issue in Tooltip?

> Plugin Health Score ([1](https://github.com/jenkins-infra/plugin-health-scoring)) is not seeing the plugin. This is not normal as the released occurred a few hours ago and the application should have updated its list of plugins from the update-center since. 

as mentioned 

it's better to not remove the Health Score and should mention the issue in the tooltip why its been not there

**Comment by alecharp** [comment]
I'd prefer not showing a  `0`. Just mention `no score` in place of the progress bar then?

**Comment by halkeye** [comment]
With https://github.com/jenkins-infra/plugin-site/pull/1394 the site no longer crashes, feel free to do a better fix

**Comment by alecharp** [comment]
Thanks @halkeye for this fix. To me, this should be enough. No scores should only happen for entirely new plugins only.

**Comment by alecharp** [comment]
@Harsh3341 if you want to work on a solution which would add a message saying why there is no score, you can. Otherwise, this is good enough for me.

**Comment by Harsh3341** [comment]
> @Harsh3341 if you want to work on a solution which would add a message saying why there is no score, you can. Otherwise, this is good enough for me.

Currently, the fix is ok I will work on such cases later😀

**Comment by krisstern** [comment]
Thank you so much for your contributions @Harsh3341!

**Comment by Harsh3341** [comment]
> Thank you so much for your contributions @Harsh3341!

More work is to be done🤝, all thanks to @halkeye @alecharp @zbynek @NotMyFault for such guidance

**Comment by alecharp** [comment]
Maybe we can change the label on this issue from `bug` to `enhancement` as the fix was done (Thanks again @halkeye) and now it's just a matter of improving the display. what do you think?

**Comment by Harsh3341** [comment]
we can close this issue now there is not much need for improving the display right now, we can work on it later on.

**Comment by halkeye** [comment]
closed as requested
