### ISSUE TITLE
Improve handling of GitHub flavored markdown - admonitions

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1403]
GitHub added a couple of custom markdown rules some time ago, to highlight notes and warnings, such as
```txt
> **Note**
> GitHub flavored markdown

> **Warning**
> and a warning
```

rendering as 

> **Note**
> GitHub flavored markdown

> **Warning**
> and a warning

on GitHub.

On plugins.j it looks really weird: https://plugins.jenkins.io/jenkins-infra-test/

I'd like to see some improvement, but I also lack the creativity to come up with a better approach.

**Comment by zbynek** [comment]
@NotMyFault are you aware of any plugin using this markdown feature?

I couldn't even find AsciiDoc admonitions, so I created https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/102, but those are not using icons, so that's probably unrelated.

**Comment by NotMyFault** [comment]
> @NotMyFault are you aware of any plugin using this markdown feature?
> 
> I couldn't even find AsciiDoc admonitions, so I created [jenkinsci/jenkins-infra-test-plugin#102](https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/102), but those are not using icons, so that's probably unrelated.

There are cases, where people use them in changelogs, such as https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.2 -> https://plugins.jenkins.io/matrix-auth/releases/

**Comment by zbynek** [comment]
Parsing releases is done by code in another repo, there is https://github.com/jenkins-infra/docker-plugin-site-issues/issues/29 for that. For readme we're ATM useng GitHub's md->html rendering so IIRC in readme the only problem with admonitions is a CSS issue, but I don't know if there is still a test-case for it.
