### ISSUE TITLE
Updating below  plugin's broke the pipeline code for ansible playbooks. 

### ISSUE THREAD

**Issue by pnayudu** [jenkins-infra/plugin-site#1433]
Problem with the [Jenkins Plugins](https://plugins.jenkins.io/) page[source file](https://github.com/jenkins-infra/plugin-site/tree/master/plugins/plugin-site/src/templates/index.jsx)
TODO: upgraded below plugin's about a week ago which is breaking pipeline scripts which run ansible playbooks. the error is "fatal: [host_anme]: UNREACHABLE! => changed=false 
  msg: |-
    Invalid/incorrect password: "

Credentials are correct and i can run the same sshpass command from CLI but jenkins gui is troubling me.

Plugins that got upgraded:
scm-api.jpi
plugin-util-api.jpi
workflow-scm-step.jpi
workflow-multibranch.jpi
pipeline-model-definition.jpi
pipeline-stage-tags-metadata.jpi
pipeline-model-extensions.jpi
workflow-job.jpi
pipeline-model-api.jpi
workflow-cps.jpi
pipeline-build-step.jpi
workflow-api.jpi
lockable-resources.jpi
jnr-posix-api.jpi
jersey2-api.jpi
jackson2-api.jpi
instance-identity.jpi
gradle.jpi
gitlab-branch-source.jpi
gitlab-oauth.jpi
gitlab-api.jpi
github-branch-source.jpi
okhttp-api.jpi
git-client.jpi
git.jpi
font-awesome-api.jpi
email-ext.jpi
echarts-api.jpi
data-tables-api.jpi
branch-api.jpi
bootstrap5-api.jpi
authorize-project.jpi

# Screenshots
TODO: Add screenshots if possible
# Possible Solution

N/A

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
