### ISSUE TITLE
Jenkins Plugins page - 503 when searching for a plugin

### ISSUE THREAD

**Issue by keberle94** [jenkins-infra/plugin-site#1434]
Problem with the [Jenkins Plugins](https://plugins.jenkins.io/) page[source file](https://github.com/jenkins-infra/plugin-site/tree/master/plugins/plugin-site/src/templates/index.jsx)
Expected: 
When entering a plugin to search in the searchbar and click search or hit enter the website should show me results for that search
Current:
When entering a plugin to search in the searchbar and click search or hit enter I get an http 503 error
# Screenshots
![image](https://github.com/jenkins-infra/plugin-site/assets/11720250/ec589417-35f0-4598-80ee-053842dfff53)

# Possible Solution
N/A

**Comment by lemeurherve** [comment]
This is related to https://status.jenkins.io/issues/2023-07-07-maintenance-aks-k8s-1-25/

We're experiencing an outage, see https://github.com/jenkins-infra/helpdesk/issues/3582 for updates.

**Comment by keberle94** [comment]
Thanks for the Info. Have a nice Weekend!
