### ISSUE TITLE
Links in headers show two anchors

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1504]
### Problem with this page

https://plugins.jenkins.io/docker-plugin/

### Expected behavior

One anchor is displayed per heading, and highlighted if you hover over it.

### Actual behavior

https://plugins.jenkins.io/docker-plugin/ (and any other page with headers), shows a static header and a blue one added on hover.
![Screenshot 2023-09-22 at 15 38 55](https://github.com/jenkins-infra/plugin-site/assets/13383509/8c2f6558-065b-4798-a0d4-bf3523cc1108)

### Possible solution

A single anchor is sufficient. Possibly, the latter, to keep the noise low and display the anchor only, if you hover over the object.

**Comment by zbynek** [comment]
Hm, the second icon was added in #1492, but looks OK in https://deploy-preview-1492--jenkins-plugin-site-pr.netlify.app/docker-plugin/

https://deploy-preview-1503--jenkins-plugin-site-pr.netlify.app/docker-plugin/ is already doubled

**Comment by halkeye** [comment]
what if its time based, github changing their markup and we are no longer hiding theirs?
