### ISSUE TITLE
Installation count line chart is flat

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1509]
### Problem with this page

https://plugins.jenkins.io/workflow-aggregator/

### Expected behavior

The line chart of installation numbers reflects the state of the plugin.

### Actual behavior

The chart is flat, 260k installations are shown at the same height as 270k installations.

**Comment by zbynek** [comment]
The graph is <100px high and the *relative* install count goes between 86.5% and 87.9%, so there should be <2px difference. Previously the graph was plotting absolute number of installs, but that swings a lot with the number of instances that send telemetry (#1499).

![stats](https://stats.jenkins.io/jenkins-stats/svg/total-jenkins.svg)
