### ISSUE TITLE
Sorting on results screen is broken

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#1510]
### Problem with this page

https://plugins.jenkins.io/ui/search/?sort=installed&categories=&labels=&view=Tiles&page=1&query=danielbeck

### Expected behavior

Sorting works

(And sorting by relevance should perhaps consider install count as well, absent reasons to sort differently)

### Actual behavior

Sorting does not work

**Comment by lemeurherve** [comment]
FWIW all sorts seem broken for me, either on Firefox or Chrome.

**Comment by daniel-beck** [comment]
@lemeurherve Good point, generalized the issue description.

**Comment by Harsh3341** [comment]
@daniel-beck I think this issue is related to #632

**Comment by krisstern** [comment]
I am interested in working on this issue for Hacktoberfest 2023

**Comment by zbynek** [comment]
Relevance sorting fixed in https://github.com/jenkins-infra/plugin-site/commit/ecf447812b72efbe4eb2e6f42490e5cf21db93c4. Other sorts to be handled in #632
