### ISSUE TITLE
No examples page

### ISSUE THREAD

**Issue by igor-teresco** [jenkins-infra/plugin-site#1519]
### Problem with this page

[Plugin page not found](https://plugins.jenkins.io/kubernetes-credentials-provider/examples) page[source file](https://github.com/jenkins-infra/plugin-site/tree/master/plugins/plugin-site/src/pages/404.jsx)

### Expected behavior

See examples

### Actual behavior

404 page

**Comment by lemeurherve** [comment]
Should be addressed by https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/79

**Comment by jtnord** [comment]
this is a smaller issue of the bigger symtom that the page shown is incorrectly generated.

e.g. 
<img width="692" alt="image" src="https://github.com/jenkins-infra/plugin-site/assets/494726/073c0ff1-9c9d-4376-9d75-f42dec4a6542">

**Comment by lemeurherve** [comment]
@jtnord is right, more details in https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/79 comments.

**Comment by zbynek** [comment]
btw. instead of Jekyll's highlight macro you can use the markdown syntax ``\`groovy ... ```, works well when rendered on GitHub and should work with Jekyll as well: https://jun711.github.io/web/how-to-highlight-code-on-a-Jekyll-site-syntax-highlighting/#example-with-language-specified

**Comment by zbynek** [comment]
Fixed in https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/pull/81
