### ISSUE TITLE
double negative ish on health scrore

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#1554]
### Problem with this page

https://plugins.jenkins.io/ldap/healthscore/

### Expected behavior

> No commit in the last 4 years. 0%

0 percent sounds bad. But it seems like from the above checks that there is comments newer than 4 years ago. So this feels like the check is inverted, if the only commits are more than 4 years ago, then negative points.

I think the check should be "had commits more recent than 4 years ago" so it sticks with convention 

Or I'm wrong and it proves my point it's confusing

![Screenshot_20231025-232034](https://github.com/jenkins-infra/plugin-site/assets/110087/5fb13650-5fef-4445-b025-5d5ea9ec6792)

### Actual behavior

Na

**Comment by zbynek** [comment]
I think this issue should be on the plugin health scoring repo, that's where this bug comes from

https://github.com/jenkins-infra/plugin-health-scoring/blob/main/core/src/main/java/io/jenkins/pluginhealth/scoring/scores/AdoptionScoring.java#L186
