### ISSUE TITLE
idea: use color in health check rows

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#1555]
Either whole row or just partial. Bootstrap has success, warn and danger colors. Could even color $percent of the background to make it easy to compare.

A white 0 next to a white 100 isn't super easy to judge

**Comment by alecharp** [comment]
I like that idea. 
I tried to used colors on the initial pull requests but my taste for color isn't great. 

I would suggest not to use `error` (or `danger` or equivalent) to anything that is not `100/100`.
Not getting a perfect score is not synonym to an error, but to a suggestion of improvement. 

For example, not having JEP-229 implemented is not a problem, a plugin can be well maintained without it. However, it could help the plugin be released more often and that would benefit the users. But it's not a problem not to have it.

**Comment by zbynek** [comment]
Maybe 0 score for important probe can be danger , for unimportant (weight 0) can be info, higher scores can be warn and success. Also to support colourblind users it would be nice to add icons (checkmark, cross, ...) .

**Comment by AayushSaini101** [comment]
@zbynek Can i work on this issue,

**Comment by zbynek** [comment]
@AayushSaini101 sure. Please open a pull request when you want to get some feedback on your work, thanks.

**Comment by Ratul-Saha-003** [comment]
Is this issue still open? Can I work on this?

**Comment by zbynek** [comment]
Fixed in https://github.com/jenkins-infra/plugin-site/pull/1593
