### ISSUE TITLE
Fix the overflow of contributor name

### ISSUE THREAD

**Issue by sridamul** [jenkins-infra/plugin-site#1571]
### Problem with this page

https://plugins.jenkins.io/ui/search/?sort=relevance&categories=&labels=&view=Tiles&page=1&query=oleg

### Expected behavior

No overflow of contributor name in the item box

### Actual behavior

Contributor name overflows into the text

![name overflow 2](https://github.com/jenkins-infra/plugin-site/assets/107404972/d5d7db3f-31ab-472c-98b9-9c6614b741fe)
![name overflow](https://github.com/jenkins-infra/plugin-site/assets/107404972/259aec7f-e198-4720-a950-2be5e7514519)

**Comment by zbynek** [comment]
Thanks, fixed in https://github.com/jenkins-infra/plugin-site/commit/f7e8d4ba0db68e2136cbf3682b2678d657a65198
