### ISSUE TITLE
Previously working docs pages no longer show plugin documentation

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#1574]
### Problem with this page

https://plugins.jenkins.io/git/

### Expected behavior

Documentation content should be visible on the page without requiring an extra click to open the GitHub source of the documentation.  Content was visible previously but has disappeared recently.

Same problem is visible for many plugins, including:

* https://plugins.jenkins.io/warnings-ng/
* https://plugins.jenkins.io/embeddable-build-status/
* https://plugins.jenkins.io/elastic-axis/

### Actual behavior

Plugin page opens with only a hyperlink to the GitHub page

![screencapture-plugins-jenkins-io-elastic-axis-2023-12-21-11_01_32-edit](https://github.com/jenkins-infra/plugin-site/assets/156685/5a165d05-fa77-4020-9b56-a416d0279ddf)

**Comment by halkeye** [comment]
that usually means it has problem pulling the data. It should get fixed on the next run. This code was in place when the plugin-site-api was still heavily used and often would time out. Probably better now to fail the build and not deploy.

**Comment by MarkEWaite** [comment]
Fixed with the latest run.  Thanks!
