### ISSUE TITLE
Plugin card view is difficult to read with dark mode enabled

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/plugin-site#1577]
When enabling dark mode, the plugin search card mode is difficult to read, given the text and health score uses almost the similar gray tone like the background:

<img width="1088" alt="Screenshot 2023-12-22 at 21 59 13" src="https://github.com/jenkins-infra/plugin-site/assets/13383509/01d633a6-656b-4215-a9ee-55a82902d16d">

**Comment by nouralmulhem** [comment]
can you assign this on me ? check this out

## **Before:**
![image](https://github.com/jenkins-infra/plugin-site/assets/76218033/0aae72fe-6044-42f8-ab42-8d521fd5d618)

## **After:**
![image](https://github.com/jenkins-infra/plugin-site/assets/76218033/6bbdefd9-8fa6-404a-9c44-edeca43ce6b4)

**Comment by NotMyFault** [comment]
Fixed in https://github.com/jenkins-infra/plugin-site/pull/1600
