### ISSUE TITLE
Remidiate the Vulnerabiltiy 

### ISSUE THREAD

**Issue by ranjithdhoosa** [jenkins-infra/plugin-site#1586]
### Problem with this page

[Jenkins Plugins](https://plugins.jenkins.io/) page[source file](https://github.com/jenkins-infra/plugin-site/tree/master/plugins/plugin-site/src/templates/index.jsx)

### Expected behavior

How to remidiate below remidiate
 "Jenkins stored cross-site scripting (xss) vulnerability (jenkins seciruty advisory 2023-07-26)"

### Actual behavior

It throwing vulnerabiltiy

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
