### ISSUE TITLE
Use `main` as primary branch

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-site#1595]
### Suggestion

We should use `main` instead of `master` as primary branch.

This will need updating not only this repo but also all references to `master` in Jenkinsfile(s) and job on ci.jenkins.io and infra.ci.jenkins.io.

### Links

- https://github.com/jenkins-infra/helpdesk/issues/2671

**Comment by NotMyFault** [comment]
Addressed in https://github.com/jenkins-infra/plugin-site/commit/8666f2543214cb2144939c263f4f35489e386c07 and hardened by https://github.com/jenkins-infra/kubernetes-management/pull/5036
