### ISSUE TITLE
Build fails with `error Type with name "JenkinsPluginHealthScore" does not exists`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-site#1723]
### Problem with this page

ci.jenkins.io & infra.ci.jenkins.io

### Expected behavior

Successful build.

### Actual behavior

Builds from primary branch fail since today, even if there is no new commit since the last successful build.

Extract from logs:
```
 [@jenkins-cd/jenkins-plugin-site]: success fetch plugins info - 56.420s
 [@jenkins-cd/jenkins-plugin-site]: success Checking for changed pages - 0.001s
 [@jenkins-cd/jenkins-plugin-site]: success source and transform nodes - 78.900s
 [@jenkins-cd/jenkins-plugin-site]: info Writing GraphQL type definitions to /home/jenkins/workspace/website-jobs_plugin-site_main/plugins/plugin-site/.cache/schema.gql
 [@jenkins-cd/jenkins-plugin-site]: error Type with name "JenkinsPluginHealthScore" does not exists
 [@jenkins-cd/jenkins-plugin-site]: 
-
TypeStorage.ts
:
39
 SchemaComposer.get
```

**Comment by lemeurherve** [comment]
Triggered a new build, no error anymore 🤷

**Comment by alecharp** [comment]
I believe that it didn't really resolved itself but we still have a problem with empty report. 
With https://github.com/jenkins-infra/plugin-site/commit/441d0bc79a7b3500df74d2f147f41298718fcf79, it should have helped but we might have used the build log to see if any errors was thrown.

**Comment by lemeurherve** [comment]
No build around the 21th April (?):

<img width="326" alt="image" src="https://github.com/jenkins-infra/plugin-site/assets/91831478/24fbecaa-b07a-4313-b7ec-79f6008e48eb">
