### ISSUE TITLE
Search on the index page of plugins.jenkins.io no longer works

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#200]
1. Go to plugins.jenkins.io
1. Enter any search term
1. Press enter and/or click the search button

Nothing happens.

**Comment by halkeye** [comment]
It certainly works for me. I think its the same issue that oleg is having on #132 where the website isn't serveing the right files, so it doesn't load the javascript bits, just leaves the static page content.

If you see it again can you try a hard refresh (https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) and see if the problem persists? 
If so - Then i really want to move off the deploy to azure + nginx proxy thing
If not - then its likely a caching heading issue.

**Comment by daniel-beck** [comment]
It works now.

Notably I tried to access the URLs above directly, and that didn't work earlier, but does work now. That's unlikely a caching issue. Perhaps related to the earlier jenkins.io downtime.
