### ISSUE TITLE
修改了配置信息，项目重新构建未使用最新配置

### ISSUE THREAD

**Issue by bgmg20171120** [jenkins-infra/plugin-site#248]
jenkins版本：2.222.1
Publish over SSH版本：1.20.1，
修改了配置信息，项目构建依然使用历史配置信息，
临时解决方案：修改历史SSH Server的Name，历史使用该配置的项目，需要将配置打开，重新保存一下
建议修改：修改Publish over SSH配置后，推送历史项目最新配置文件

**Comment by oleg-nenashev** [comment]
@bgmg20171120 please convert this issue to English
