### ISSUE TITLE
Unable to download plugin from download site

### ISSUE THREAD

**Issue by ingoman** [jenkins-infra/plugin-site#252]
Problem with the [Active Directory](https://plugins.jenkins.io/active-directory) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/srctemplates/plugin.jsx)

TODO: 
Actually I can't download the active directory plugin (active-directory.hpi) from the download site 
https://updates.jenkins.io/download/plugins/active-directory/
I always get the message "The requested URL /plugins/active-directory/2.16/active-directory.hpi was not found on this server."

Best Regards 
Ingo

**Comment by halkeye** [comment]
Hi @ingoman 

Sometimes the mirrors take a little bit of time to update after the release. The link seems to be working now.

If this isn't working for you still, I will suggest opening an infra ticket on https://issues.jenkins-ci.org/secure/Dashboard.jspa so the mirror configs can be tweaked.
