### ISSUE TITLE
[Report a problem] template page is missing a slash when linking to the github file

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#254]
see https://github.com/jenkins-infra/plugin-site/issues/252

Should be https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx
but is https://github.com/jenkins-infra/plugin-site/tree/master/srctemplates/plugin.jsx 
(note the srctemplates vs src/templates)

**Comment by contactsaurabh** [comment]
Hi halkeye ,

I am looking to fix this issue. Can you please point me to the place where this link actually is, so that i can fix this . 

I am new to contributing, I hope you will understand, if this is something uncommon to ask for :)

Thanks!

**Comment by zbynek** [comment]
@contactsaurabh  in code it's here:
https://github.com/GuelorEmanuel/plugin-site/blob/cf7d3ae54e7c141c271150d5ba9650c4307b78d3/src/components/ReportAProblem.jsx#L9

on the website it's in the footer ("Report a problem" in the footer e.g. here https://plugins.jenkins.io/active-directory/ )

**Comment by contactsaurabh** [comment]
Thanks @zbynek .

**Comment by contactsaurabh** [comment]
When I am going to fix this issue by forking. I do not see this file listed under src/components 

https://github.com/contactsaurabh/plugin-site/tree/master/src/components 

Is this moved or something else.

**Comment by contactsaurabh** [comment]
Fixed the file and pushed the changes

**Comment by halkeye** [comment]
Note you put the pr on the fork not this repo. I didn't catch zybneks link in time.

Can you resubmit the pr for the jenkins-infra repo?

**Comment by contactsaurabh** [comment]
Hi halkeye, 
I am very new in this github world, so I am sorry, If I did something wrong here. 

Will try again today. 

Thanks !!

**Comment by halkeye** [comment]
It's all good. Zybnek originally gave you

https://github.com/GuelorEmanuel/plugin-site/blob/cf7d3ae54e7c141c271150d5ba9650c4307b78d3/src/components/ReportAProblem.jsx#L9

But it should be

https://github.com/jenkins-infra/plugin-site/blob/master/src/components/ReportAProblem.jsx#L9

So the problem is that the pull request is on GuelorEmanuel's copy not the official jenkins-infra copy.

Easiest solution is to goto https://github.com/jenkins-infra/plugin-site, if it has a yellow bar talking about your branch follow that. Else goto the pull request tab. Create a new pull request, select across forks, then choose your fork.

Im mobile right now or I'd give more concrete instructions, but hopefully that'll lead you in the right direction. If you really get stuck feel free to join https://gitter.im/jenkinsci/docs and maybe someone can give you a hand while I sleep/work

**Comment by halkeye** [comment]
Oh sweet you figured it out while I was writing :)

**Comment by contactsaurabh** [comment]
Hey , thanks a lot.  Was just trying . :)
