### ISSUE TITLE
[Report a problem] reporting a problem on a plugin page should goto plugin issues

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#255]
For now direct link to jira

when jira/github gets decided on, and exposed, then should goto the right place.

**Comment by contactsaurabh** [comment]
Hi  @halkeye,

I would like to fix this, if that is ok.  

Can you please pass on the code location for this .

Thanks!

**Comment by halkeye** [comment]
Totally okay for you to fix it.

We had people reporting plugin docs issues in the plugin site - example https://github.com/jenkins-infra/plugin-site/issues/267

As for where, thats up to you a bit, but I would say the same as the previous issue, src/components/ReportAProblem.jsx
Have that file look at the page being provided, if its a plugin page, goto jira instead of plugin-site github


See https://confluence.atlassian.com/jirakb/how-to-create-issues-using-direct-html-links-in-jira-server-159474.html

Only thing we need to provide is `component=$pluginName.replace(/-plugin$/, '')` (to remove any extra -plugin that some plugins have)

Does that make sense?

**Comment by tkelley-eg** [comment]
> Totally okay for you to fix it.
> 
> We had people reporting plugin docs issues in the plugin site - example #267
> 
> As for where, thats up to you a bit, but I would say the same as the previous issue, src/components/ReportAProblem.jsx
> Have that file look at the page being provided, if its a plugin page, goto jira instead of plugin-site github
> 
> See https://confluence.atlassian.com/jirakb/how-to-create-issues-using-direct-html-links-in-jira-server-159474.html
> 
> Only thing we need to provide is `component=$pluginName.replace(/-plugin$/, '')` (to remove any extra -plugin that some plugins have)
> 
> Does that make sense?

I spent a little time trying to make sure I understand this.  I'm new to the Jenkins OSS ecosystem, so I have some basic questions.

It seems like we're saying that **all** of the actual plugin issues are managed in JIRA and not GitHub?  It looks like the plugins are defined using JIRA components.  Based on the reference confluence article, it seems that we can build a URL that will specify the proper component name when directing the user to JIRA to create the issue.  Your `replace` logic seems to serve to correct the mismatch between the plugin site URL and the JIRA component name, where a site might be `https://github.com/jenkinsci/vsts-cd-plugin-plugin` and the JIRA component name doesn't include the final `-plugin`.

![image](https://user-images.githubusercontent.com/3812023/96656877-c0cc0c80-130e-11eb-9f73-cd8888af2398.png)


Finally, it seems we are wanting to update the link in the footer when the user is on a plugin page?  

![image](https://user-images.githubusercontent.com/3812023/96656704-6468ed00-130e-11eb-9c4b-6c8d31150f1f.png)

**Comment by halkeye** [comment]
> It seems like we're saying that **all** of the actual plugin issues are managed in JIRA and not GitHub?

officially so far yes, adding in github support is on the todo list, but not done yet. Infact I was thinking at poking update center this weekend to fix that and to return the default branch.

Could add a issues url to https://github.com/jenkins-infra/plugin-site-api/blob/master/src/main/java/io/jenkins/plugins/models/Plugin.java for now, and have it always return jira, so when we do fix it, we don't need to update everything else.

> Finally, it seems we are wanting to update the link in the footer when the user is on a plugin page?

I don't have a good solution for this. I do think "Report a problem" is part of the problem. "Report a problem with this page" or "Report plugin site problem" would be more wordy, but possibly more clear.

But yea, the original thinking of mine was just to reduce the number of non plugin site reported bugs, like https://github.com/jenkins-infra/plugin-site/issues/401 so open to any and all solutions. Honestly though, when people are frustrated, they want simple, and there's nothing else on the page indicating how to report issues.

**Comment by timja** [comment]
I think we should add GitHub issues support before adding this...

**Comment by tkelley-eg** [comment]
> I think we should add GitHub issues support before adding this...

Could you expand a bit on what that means?  My guess is that we would have data available via graphql to see if a plugin project uses GitHub for issues so that we can build a `Report a problem` link in a similar way that we build it for this site?  Or, we would hit the GitHub API to check the same?

**Comment by timja** [comment]
Good guess, yeah basically that's it, the plugin-site-api needs to return the issue tracker location and then UI should route appropriately to jira or github, (not sure if you can set components via url with jira, but ideally link to the new issue page)
