### ISSUE TITLE
Reduce category header size in the changelog entries

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#262]
IMHO the category header is too big. Currently it is `h2` with a size of 2rem:

![image](https://user-images.githubusercontent.com/3000480/84132729-81c7a980-aa46-11ea-897a-fbcab21d7088.png)

## Suggestion

if we reduce it, it would look much better.

### 1.2 rem

![image](https://user-images.githubusercontent.com/3000480/84132992-d79c5180-aa46-11ea-9327-907042c074e5.png)

### 1.1rem

![image](https://user-images.githubusercontent.com/3000480/84133117-0ca8a400-aa47-11ea-87ab-e34d818a3a14.png)

**Comment by sachinmukherjee** [comment]
@oleg-nenashev Can I take this issue?

**Comment by oleg-nenashev** [comment]
Sure! Thanks for your interest

**Comment by tkelley-eg** [comment]
I did a little bit of analysis on this in an effort to learn some new things.  I might be missing something very simple...

The content for the `Releases` cards are retrieved through an API call, which returns HTML with the `<h2>` tag.

https://github.com/jenkins-infra/plugin-site/blob/d4997eba8dad3e08279ed8feb84d032c664585fd/src/components/PluginReleases.jsx#L16

![image](https://user-images.githubusercontent.com/3812023/96062775-87a22100-0e64-11eb-9247-3313db38fb9e.png)

The code on the API side, pulls release data directly from GitHub:

https://github.com/jenkins-infra/plugin-site-api/blob/921cc1eb4c2b2bdef791cbdfd9c9b27e4eec5b81/src/main/java/io/jenkins/plugins/services/impl/HttpClientReleases.java#L41

But the GitHub API returns Markdown, which is then translated (again in the API code) to the `bodyHTML` JSON element.

https://github.com/jenkins-infra/plugin-site-api/blob/921cc1eb4c2b2bdef791cbdfd9c9b27e4eec5b81/src/main/java/io/jenkins/plugins/models/PluginRelease.java#L35

![image](https://user-images.githubusercontent.com/3812023/96062973-f0899900-0e64-11eb-9601-7b5e8ae50777.png)

The question is - should we introduce some CSS to specifically target the elements with something like:

`.card-body .card-text h2`

**Comment by halkeye** [comment]
Good investigation, you got it exactly right.

> The question is - should we introduce some CSS to specifically target the elements with something like:

Yea, as long as its scoped to the page

#pluginPage #pluginReleases--container .card-body .card-text h2 {
}

ish
