### ISSUE TITLE
Add support for GitHub Issues listing

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#264]
Currently the plugin site uses Jenkins Jira. Many plugins use GitHub Issues, and for them we still display Jira. E.g. https://plugins.jenkins.io/configuration-as-code/#issues , CC @timja @jetersen . I am not sure what is missing there, maybe we just need to get the update center metadata over the line

**Comment by halkeye** [comment]
Note this is mostly in plugin-site-api

**Comment by timja** [comment]
@zbynek FYI I was just checking out your issue tracker PRs in prod and it seems the issues that display in plugin site are still using Jira.


https://plugins.jenkins.io/azure-ad/#issues
https://plugins.jenkins.io/slack/#issues

But apart from that it looks great! Thanks!

**Comment by zbynek** [comment]
@timja personally I'd suggest to just remove the issues tab and let people follow the "open issues" link. But I think @halkeye has a different opinion on this :)

**Comment by halkeye** [comment]
fixed as of #1159
