### ISSUE TITLE
Bitbucket Pullrequest Builder page - TODO: Does this support for bitbucket Datacenter

### ISSUE THREAD

**Issue by ManjunathRNayak** [jenkins-infra/plugin-site#267]
Hi Team, 
As mentioned in the Doc the following line states that this plugin will be able to connect to bitbucket.org (cloud).
"This plugin builds pull requests from Bitbucket.org and will report the test results. Basic documentation can be found on GitHub."
Can you confirm on this that if this supports the same functionality with bitbucket datacenter as same as it functions with bitbucket cloud?

Thanks in advance.

Regards,
Manjunath R

**Comment by timja** [comment]
Hi this repository is for issues relating to the site itself, can you ask the question directly to the plugin maintainers? It appears they have issues open here: https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin

**Comment by oleg-nenashev** [comment]
Just another repository where we have a conflict between forks. https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin is supposed to be used for such purpose...

**Comment by timja** [comment]
Yeah 😢
