### ISSUE TITLE
Search page - single-colum layout is broken on mobile

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#273]
Problem with the [Search](https://plugins.jenkins.io/ui/search?query=) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/srctemplates/search.jsx)

Single-column layout looks bad on mobile

## Screenshots 

 Android/Chrome:

![Screenshot_20200610-221431_Chrome](https://user-images.githubusercontent.com/3000480/84314392-44f3d380-ab68-11ea-9e0e-fbceccd4b1c8.jpg)

## Possible Solution 

 

* fix minimum width, reallign controls

**Comment by halkeye** [comment]
Which device are you using? My 4 xl is fine but the media queries might be off 

![Screenshot_20200610-142208](https://user-images.githubusercontent.com/110087/84320027-e0178980-ab25-11ea-9cf9-41d75412a375.png)

**Comment by oleg-nenashev** [comment]
@halkeye there are 3 modes in the top, try the third one

**Comment by halkeye** [comment]
Oh yep solo broken :)

**Comment by zbynek** [comment]
The PR #400 fixes the card layout, but not the list layout.
