### ISSUE TITLE
Team Concert page - "master" and "slave" used in doc can be removed

### ISSUE THREAD

**Issue by contactsaurabh** [jenkins-infra/plugin-site#276]
Problem with the [Team Concert](https://plugins.jenkins.io/teamconcert) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: 

Expected: No "slave" mention in document.

Actual: Found the below mention :
(https://plugins.jenkins.io/teamconcert/)
Under RTC topic
"For all the supported build configurations - Build Definition, Repository Workspace, Stream and Snapshot - a valid build toolkit should be present on both the **master and slave** machines and the Jenkins jobs should be configured to use this toolkit."

## Screenshots 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/44664783/85121109-d8509700-b241-11ea-9ddb-b69ec6a97418.png">

## Possible Solution 
Edit page such that "master" and "slave" used in doc can be removed

**Comment by oleg-nenashev** [comment]
The plugin documentation is still hosted on Jenkins Wiki. To fix it, we
need to migrate docs to GitHub:
https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/

Any contributions here would be appreciated!

**Comment by contactsaurabh** [comment]
Sure , will contribute here.
