### ISSUE TITLE
Plugin releases page - Github PR links are broken

### ISSUE THREAD

**Issue by wwuck** [jenkins-infra/plugin-site#291]
Problem with the [OWASP Markup Formatter](https://plugins.jenkins.io/antisamy-markup-formatter) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

I am browsing the new/recently added Releases tab on any of the plugins pages.  Clicking on one of the Github Pull Request links goes to a 404 page on plugins.jenkins.io instead of going to the Github Pull Request page.

E.g. https://plugins.jenkins.io/antisamy-markup-formatter/issues/22

## Possible Solution 

This is similar to https://github.com/jenkins-infra/plugin-site/issues/255 and https://github.com/jenkins-infra/plugin-site/issues/264 but not identical as those bugs are related to Github Issues and not Pull Requests, however it might be considered a duplicate since the Github issues url redirects to the pull request if given the correct PR number in the url.

E.g. if https://plugins.jenkins.io/antisamy-markup-formatter/issues/22 is converted to https://github.com/jenkinsci/antisamy-markup-formatter-plugin/issues/22 then Github will redirect to the correct PR/pull url at https://github.com/jenkinsci/antisamy-markup-formatter-plugin/pull/22.  Should the links be changed to go directly to the PR/pull url or is it ok to rely on github redirecting from the issues url?

**Comment by halkeye** [comment]
Oh here is way more visible, but I documented the solution https://github.com/jenkins-infra/plugin-site-api/issues/88 but havn't gotten to it yet.

**Comment by timja** [comment]
Closed in https://github.com/jenkins-infra/plugin-site-api/pull/92
