### ISSUE TITLE
Move the plugin name above the tabs && show it for all tabs

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#306]
Currently the plugin name is shown only on the documentation tab.
I propose to move it up above the tabs and to display it for all tabs.

Current plugin version can be moved to a separate row within the documentation or kept as is now

![image](https://user-images.githubusercontent.com/3000480/87308984-4a07c200-c51c-11ea-80ec-dbad6ad6eb56.png)

**Comment by sachinmukherjee** [comment]
@oleg-nenashev Can I take this issue?

**Comment by oleg-nenashev** [comment]
Yes!

**Comment by sachinmukherjee** [comment]
Hi @oleg-nenashev  Where can I find this page? I have built this project and started the dev server using the command yarn dev. But I can see totally different page 
![image](https://user-images.githubusercontent.com/19318218/92989128-69f13d00-f4ef-11ea-9376-c01b57175d83.png)

**Comment by oleg-nenashev** [comment]
Please open any plugin page

**Comment by sachinmukherjee** [comment]
I have made the changes according to the issue description and it looks like this:
![image](https://user-images.githubusercontent.com/19318218/93000278-f9750b00-f544-11ea-9dc2-0a02f4a6eb51.png)
Few questions:

- Should I remove the plugin name resides below the documentation tab.

- Should I change the plugin title heading(currently h1) located above all the tabs to something else

**Comment by halkeye** [comment]
> Should I remove the plugin name resides below the documentation tab.

Yes once globally is fine and looks way better

> Should I change the plugin title heading(currently h1) located above all the tabs to something else

Like smaller text or anything? I think it's fine as is

**Comment by oleg-nenashev** [comment]
+1 to what @halkeye says.

**Comment by halkeye** [comment]
This was handled by #363
