### ISSUE TITLE
GitHub page - documentation link incorrect?

### ISSUE THREAD

**Issue by dblees** [jenkins-infra/plugin-site#307]
Problem with the [GitHub](https://plugins.jenkins.io/github) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Link is https://github.com/jenkinsci/github  .. which results in a 404
however this seems valid: https://github.com/jenkinsci/github-plugin .. which works and shows 1.3.0 as current version.

## Screenshots 

 TODO: Add screenshots if possible 
![github-plugin-screenshot-1](https://user-images.githubusercontent.com/10382997/87323774-35680180-c4fd-11ea-9dc4-2bb422bce6c9.PNG)

## Possible Solution 

Just update to correct link please.

N/A

**Comment by oleg-nenashev** [comment]
Release of https://github.com/jenkinsci/github-plugin/pull/232 should fix that. CC @timja @KostyaSha

**Comment by KostyaSha** [comment]
will make release in a next days

**Comment by oleg-nenashev** [comment]
Thank you!

**Comment by KostyaSha** [comment]
Unable to make release because of auth errors.

**Comment by timja** [comment]
You'll need to reset your password as detailed in https://groups.google.com/g/jenkinsci-dev/c/3UvrCTflXGk/m/kJVRpkCYAwAJ

**Comment by KostyaSha** [comment]
It doesn't work. Anyway @oleg-nenashev helped and i released

**Comment by oleg-nenashev** [comment]
The plugin documentation now works correctly. Thanks for the fix @timja @KostyaSha !

**Comment by oleg-nenashev** [comment]
And thanks for reporting the issue @dblees !
