### ISSUE TITLE
Bitbucket page - PR Links swapped

### ISSUE THREAD

**Issue by MartinEmrich** [jenkins-infra/plugin-site#310]
Just a cosmetic/confusing minor problem with the [Bitbucket](https://plugins.jenkins.io/bitbucket) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

In the history, PR-63 and PR-58 seem to be the other way around.

## Possible Solution 

Swap the changelog entries, PRC-63 is PR-58 and vice-versa.

**Comment by halkeye** [comment]
Are you talking about the changelog at the bottom of the page? or the releases tab (which seems empty).

Docs are pulled from the github readme, so you should make a PR or an issue for the plugin directly and not the site code/issues.

https://github.com/jenkinsci/bitbucket-plugin/blob/master/README.md

**Comment by MartinEmrich** [comment]
yes, indeed, it's wrong in that README file.
