### ISSUE TITLE
Powershell-plugin 1.4 breaks script code with param

### ISSUE THREAD

**Issue by luckyhsif** [jenkins-infra/plugin-site#314]
When Powershell-plugin 1.4 creates a temp Powershell script file, it inserts a new line of code as the first line of the file. The new line is either,
`$ErrorActionPreference="Continue"` (When "Stop on Errors" option is unchecked)
or, 
`$ErrorActionPreference="Stop"` (When "Stop on Errors" option is checked)

This insertion breaks original code with param() because it must be the first line. An exception was thrown saying, "The term 'param' is not recognized as the name of a cmdlet, function, script file, or operable program.".

The "ErrorActionPreference" line should be taken off, code developers can certainly manage it by themselves. Or, it should be inserted after the param() block.

Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-63153

**Comment by halkeye** [comment]
I'm happy to see that a jira ticket is created but I'm closing this as its off topic, as this is supposed to be issue with the plugin site directly.
