### ISSUE TITLE
Gatling page - TODO: Put a summary here

### ISSUE THREAD

**Issue by kurmiyadla** [jenkins-infra/plugin-site#325]
Problem with the [Gatling](https://plugins.jenkins.io/gatling)  [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: I'm getting the gatling report pushed to my jenkins job area by using 'gatlingArchive()' function. Simulation result is being pushed okay too. But when I try to open the link, it's triggering a download to my disc, instead of rendering the result in html format in jenkins.

## Screenshots 

 
![image](https://user-images.githubusercontent.com/61384565/88854393-3799b380-d1bf-11ea-8622-ee34b6df2eb1.png)

## Possible Solution 

N/A

**Comment by timja** [comment]
in the latest version of the plugin I think they changed to download only to get around content security policy issues

**Comment by halkeye** [comment]
The issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
