### ISSUE TITLE
Kubernetes page - TODO: Add support for kubernetes Jobs

### ISSUE THREAD

**Issue by ghost** [jenkins-infra/plugin-site#326]
I need to run performance tests with varied parameters(for example number of parallel jobs) using Jenkins pipeline. Tests should run in parallel so Kuberntes Job is the best choice for that. When I'm starting a pipeline with the following code:
```
pipeline {
  agent any
  stages {
    stage('Running Jmeter') {
      agent {
        kubernetes {
            label "jmeter_tests_executor"
            yaml '''
apiVersion: batch/v1
kind: Job
metadata:
    name: jmeter
    namespace: jenkins
spec:
  parallelism: 2
  completions: 2
  backoffLimit: 1
  ttlSecondsAfterFinished: 100
  ...   
```
Pipeline hangs trying to schedule a task:
```All nodes of label ‘jmeter_tests_executor’ are offline...```
When I run that manifest directly on kubernetes cluster it works without any problems.
Is it possible to implement this using your plugin? Do you have a plan to make it possible?
Probably you know another options how to do it, but I should be able to **run them in parallel,get logs during/after execution**. 
Will appreciate you help as it's not rather popular issue.

**Comment by halkeye** [comment]
Thank you very much for the ticket. These tickets should be about bugs on the plugin site, for general support I would recommend the jenkins users mailing list - https://groups.google.com/forum/#!forum/jenkinsci-users - or creating a jira issue for the plugin - https://issues.jenkins-ci.org/secure/Dashboard.jspa - so the plugin author can reply.
