### ISSUE TITLE
Config File Provider page - Authorization and Permission

### ISSUE THREAD

**Issue by sqmer** [jenkins-infra/plugin-site#335]
Enhancement for the [Config File Provider](https://plugins.jenkins.io/config-file-provider) page, 

TODO: I would like to allow certain people to have access to this plugin as read-only and other as read-write permissions

If possible to add this plugin to the Project-based Matrix Authorization Strategy and Role-Based Strategy.

**Comment by oleg-nenashev** [comment]
Hello. Please report plugin issues and feature requests in the Jenkins issue tracker. These GitHub Issues section are only for the plugin site itself. How to report an issue: https://www.jenkins.io/participate/report-issue/
