### ISSUE TITLE
Release Helper page - Ticket Editor not working with custom fields

### ISSUE THREAD

**Issue by derlarsschneider** [jenkins-infra/plugin-site#336]
Problem with the [Release Helper](https://plugins.jenkins.io/release-helper) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Actual: Trying to add values to a custom field of type label. Plugin reports
java.lang.RuntimeException: Field with the name "Build Version" does not exist!

Expected: Field is amended with the given value.

## Screenshots 

N/A

## Possible Solution 

N/A

**Comment by derlarsschneider** [comment]
I have to correct myself. This does not apply to all Custom Fields but to the new fields I created. Is there a way to update the list of Custom Fields?

**Comment by halkeye** [comment]
The issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
