### ISSUE TITLE
Pipeline: Stage View page - github link goes to wrong location

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site#350]
Problem with the [Pipeline: Stage View](https://plugins.jenkins.io/pipeline-stage-view) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The github link redirects to https://github.com/jenkinsci/pipeline-stage-view-plugin/pipeline-stage-view which is a 404

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by halkeye** [comment]
![image](https://user-images.githubusercontent.com/110087/92420507-9c361f80-f128-11ea-8637-ad386bd781cf.png)

plugin-site-api is returning that url for scm

**Comment by halkeye** [comment]
https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/ui/pom.xml#L35

sub modules have confused the api for a while now. I'll dig into if its api or upstream on updatecenter

**Comment by halkeye** [comment]
$ curl -qLs 'https://updates.jenkins.io/update-center.actual.json' | jq '.plugins."pipeline-stage-view".scm'
"https://github.com/jenkinsci/pipeline-stage-view-plugin/pipeline-stage-view"

This is something update-center does

**Comment by halkeye** [comment]
Looking at the pom file
```
  <scm>
    <connection>scm:git:git://github.com/jenkinsci/pipeline-stage-view-plugin.git/pipeline-stage-view</connection>
    <developerConnection>scm:git:git@github.com:jenkinsci/pipeline-stage-view-plugin.git/pipeline-stage-view</developerConnection>
    <tag>pipeline-stage-view-2.15</tag>
    <url>https://github.com/jenkinsci/pipeline-stage-view-plugin/pipeline-stage-view</url>
  </scm>
```

[pom_xml.txt](https://github.com/jenkins-infra/plugin-site/files/5185539/pom_xml.txt)

I think its upstream in the plugin pom ... plugin

**Comment by timja** [comment]
Do we take from either scm or top level? As it’s explicitly defining one at the top level but probably not inside scm

**Comment by halkeye** [comment]
Looks like update center will grab the one from top level of it's not defined. But the pom has it defined.

**Comment by timja** [comment]
Hmm the pom doesn't define an SCM block:
https://github.com/jenkinsci/pipeline-stage-view-plugin/blob/master/ui/pom.xml#L45

must be inherited.

JCasC does define one:

https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/pom.xml#L98

**Comment by timja** [comment]
https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/105

**Comment by halkeye** [comment]
> JCasC does define one:

I can investigate tomorrow but I suggest seeing what it's pom says. I think the plugin pom might be overriding it for sub modules?

**Comment by halkeye** [comment]
@timja do you want me to investigate the pom for casc? or should we close this ticket?

**Comment by timja** [comment]
i think it's okay although would be good to fix the pom at some point
