### ISSUE TITLE
Credential not listed

### ISSUE THREAD

**Issue by shimatai-mobees** [jenkins-infra/plugin-site#362]
After creating a credential, plugin doesn't list new credential in Jenkins setup page neither in job setup page.

Jenkins version: 2.249.1 (installed with apt-get)
OS: Ubuntu Linux in AWS

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
