### ISSUE TITLE
CVSRoot in Project not accepted

### ISSUE THREAD

**Issue by DirkHa** [jenkins-infra/plugin-site#371]
Problem with the [CVS](https://plugins.jenkins.io/cvs) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: I try to save the properties of my project, the CVS Root ist set but when saving the project i get this error
## Screenshots 
![JenkinsCVS1](https://user-images.githubusercontent.com/4198371/94007935-73598f80-fda2-11ea-90ae-1fb79315bb65.png)

![JenkinsCVS2](https://user-images.githubusercontent.com/4198371/94008032-9ab05c80-fda2-11ea-9560-d21e878b687a.png)

I use Jenkins 2.258 with   CVS Plugin Version 2.16.

I need help, because i cannot change any of my projects.

## Possible Solution 

 

N/A

**Comment by DirkHa** [comment]
This happens since i updated to the new version of Jenkins 2.258, with 2.257 all works fine

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
