### ISSUE TITLE
GitHub Branch Source page - configuring Github API usage rate limiting strategy with casc is broken

### ISSUE THREAD

**Issue by frank273** [jenkins-infra/plugin-site#376]
Problem with the [GitHub Branch Source](https://plugins.jenkins.io/github-branch-source) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

setting the apiRateLimitChecker in the Github API Configuration via config-as-code results in a broken GUI setting in the Jenkins global config (see screenshot below)

```
gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
    ...
```

basically you can only set those values with casc:
* ThrottleForNormalize
* ThrottleOnOver
* NoThrottle 

as this is exposed as enum value ... so all other values are blocked anyway. So the casc part seems to be correct, but as soon as it is deployed with any of those values, the GUI setting gets broken. You cannot change the value anymore there, as the list only contains the one selected value (untranslated).

## Screenshots 

 screenshots of broken UI after rolling out with config-as-code
![image](https://user-images.githubusercontent.com/3624564/94537777-7c83aa00-0243-11eb-9b8c-39d44043ce8e.png)

## Possible Solution 
It might be just a display bug ?

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
