### ISSUE TITLE
Move "Running the App" documentation to Contributing Guidelines

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site#377]
Information in https://github.com/jenkins-infra/plugin-site#running-the-app is needed for users, not contributors. It would be great to move it to https://github.com/jenkins-infra/plugin-site/blob/master/CONTRIBUTING.md so that potential contributors can easily discover it

**Comment by halkeye** [comment]
Who are the users in this case?

**Comment by oleg-nenashev** [comment]
Indeed README does not have much value for plugins.jenkins.io users. There could be some top-level overview and a link to the contributing guide. Alternative solution is to make sure that CONTRIBUTING references README

**Comment by halkeye** [comment]
Ah, users are the ones hitting the site. 👍 just wanted to make sure things were aligned

**Comment by sachinmukherjee** [comment]
Can I take this issue?

**Comment by halkeye** [comment]
Totally yours

**Comment by sachinmukherjee** [comment]
Should I create a new section for running the app info? For example like this
# Contributing Guide
# Running the app

or just put everything under Contributing Guide
