### ISSUE TITLE
Ansible Tower page - TODO: Credentials not working for Promotions (works for Builds)

### ISSUE THREAD

**Issue by waedekin** [jenkins-infra/plugin-site#378]
When we use the Tower Plugin in a Freestyle Jenkins Promotion step,  the credentials field is not passing the value to Tower job to override the credentials in  the Job Template.   We did notice that if we put in a bogus value in the Jenkins plugin Tower does report the credentials does not exist.   Remember this is just when we use the plugin in a promotion step, this all works perfectly if we use the plugin in a build step.  

TODO: Describe the expected and actual behavior here 

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
