### ISSUE TITLE
docker-build-step page - TODO: Put a summary here

### ISSUE THREAD

**Issue by gyurovb** [jenkins-infra/plugin-site#401]
Problem with the [docker-build-step](https://plugins.jenkins.io/docker-build-step) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The documentation is misleading
at the 
"Set Docker URL" section, it is mentioned
"For other nodes, you may need to set something like http://127.0.0.1:2375"
Setting such URL leads to
"Something went wrong, cannot connect to http://172.16.1.12:2376, cause: null"
Log shows
"Unsupported protocol scheme found: 'http://172.16.1.12:2376'. Only 'tcp://' or 'unix://' supported."
Switching to 
 tcp://172.16.1.12:2376
Seems solves the issue

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
