### ISSUE TITLE
Job description with garbled characters

### ISSUE THREAD

**Issue by clockwiser** [jenkins-infra/plugin-site#430]
Problem with the [Job Import](https://plugins.jenkins.io/job-import-plugin) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 
The job description in remote jenkins server is in Japanese of UTF-8. After pressing query button, the list shows up the
job lists from remote jenkins server, but the job description is garbled.
## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 
In the following part of source, couldn't find handling of UTF encoding.

file: src\main\java\org\jenkins\ci\plugins\jobimport\client\RestApiClient.java

DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
                factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
                factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
                factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
                factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);

 
Somthing like below, directly handle UTF-8. Or use another configuration parameter.

InputStream inputStream= new FileInputStream(completeFileName);
        Reader reader = new InputStreamReader(inputStream,"UTF-8");
        InputSource is = new InputSource(reader);
        is.setEncoding("UTF-8");

        DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
        DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
        Document doc = dBuilder.parse(is);
N/A

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
