### ISSUE TITLE
GitHub page - the illustrative graphics are tiny, illegible

### ISSUE THREAD

**Issue by larrywest** [jenkins-infra/plugin-site#441]
Problem with the [GitHub](https://plugins.jenkins.io/github) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The graphics are so tiny they are impossible to read (too few pixels) and it's hard to be sure what in Jenkins they are meant to refer to.  It's not a matter of browser scaling.

One example: https://github.com/jenkinsci/github-plugin/blob/master/docs/images/ghserver-config.png

(I _think_ that says "GitHub Server Config", which is what the text says - but isn't it called "GitHub plugin"?  Or is this somewhere else?)

A worse example: https://github.com/jenkinsci/github-plugin/blob/master/docs/images/manage-token.png

## Screenshots 

![image](https://user-images.githubusercontent.com/8009072/97208115-03ab3b80-1778-11eb-8e1e-d5b468e4c64c.png)

## Possible Solution 

Replace the screenshots with larger images

**Comment by halkeye** [comment]
oooh, a legit ticket for the plugin site!

Sadly its not a problem with the plugin site, but the upstream images for the github plugin. Can you create a jira issue on issues.jenkins-ci.org/

cc @KostyaSha incase they see it here first, the wiki exporter should allow you to re-export with non thumbnails. I think the original version pulled the wrong source images.

**Comment by larrywest** [comment]
Sorry, I've tried about 10 times, but am unable to get past the captcha at issues.jenkins-ci.org, even though I skipped several I wasn't sure about.

**Comment by larrywest** [comment]
OMG.  No, it was a website screw-up: it was _telling_ me I needed to enter the Captcha correctly, but it was actually the wrong password. 😠

**Comment by larrywest** [comment]
[JENKINS-64042](https://issues.jenkins-ci.org/browse/JENKINS-64042).

**Comment by KostyaSha** [comment]
@timja cc
