### ISSUE TITLE
Job Import page - TODO: Put a summary here

### ISSUE THREAD

**Issue by jgajaan** [jenkins-infra/plugin-site#442]
Problem with the [Job Import](https://plugins.jenkins.io/job-import-plugin) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

When we import jobs that is in folders, we are getting invalid character "\" message

## Screenshots 

![Screenshot 2020-10-26 172709](https://user-images.githubusercontent.com/54897528/97230674-bdbe9980-17b0-11eb-99c2-61b3e481f707.jpg)

## Possible Solution 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)

**Comment by jgajaan** [comment]
Hi, 

This is a functionality issue - Since the jobs are under a folder the "\" separator character is marked as unsafe. Normal jobs can be imported. We have no way of not using that character  to import a job from folder

**Comment by halkeye** [comment]
Understandable, but this is issue tracker for the plugin site, not the plugin your talking about.

I recommend recording a bug at https://issues.jenkins-ci.org/
