### ISSUE TITLE
Checksum mismatch for Nexus Platform plugin

### ISSUE THREAD

**Issue by selste** [jenkins-infra/plugin-site#443]
Good morning,
we're in the process of automating the setup of Jenkins and ran into a problem during the installation of the Nexus Platform plugin (nexus-jenkins-plugin):
The checksum for release 3.9.20200722-164144.e3a1be0 is wrong (as reported by the Update Center).
We've also downloaded the plugin from Sonatype directly and verified that the checksum provided by them is correct.

Seems that something went wrong during the creation of the JSON file for the Update Center.
We also found that this is not an isolated event, e.g. the checksum for release 3.8.20200310-130318.c482b58 is wrong as well.
Regards,

Steffen Elste

**Comment by zbynek** [comment]
Thanks for the report. The hpi file located in
http://updates.jenkins.io/latest/nexus-jenkins-plugin.hpi
has SHA1 sum `QIqcTDikvBpyaHC2bCZkwsJZvTY=`
and SHA256 sum `pL+Obdw1nNZIF/Nq6Ih1lPXvg7jTF4y5ETbBvdHTTP8=`
(both checksums are base64 encoded, computed locally using
```
sha1sum nexus-jenkins-plugin.hpi | cut -f1 -d\  | xxd -r -p | base64
```
)
These are matching  the values from https://updates.jenkins.io/current/update-center.json

>  We've also downloaded the plugin from Sonatype directly and verified that the checksum provided by them is correct.

Sorry, I'm not sure how to get the checksum from Sonatype, could you please share it here?
Maybe you are trying to compare base64 encoded checksums with hexadecimal ones?

**Comment by selste** [comment]
Good morning,
sorry for the late response.
Had to dig a little deeper, but we found the problem.

We're using a Nexus Repository Proxy, and in addition to jenkins.io we also mirror Maven Central. And Maven Central also has this plugin available ... but with a different size and - obviously - a different checksum.
And unfortunately the plugin from Maven Central was taken (because it is the first entry in the list of repositories to contact).
We're going to notify Sonatype (we're a paying customer) to fix this.
Thanks,

Steffen Elste
