### ISSUE TITLE
Looking for collaborators: Redesign of archives pages

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#463]
There is no reason other than my lack of front-end/design skills that https://updates.jenkins.io/download/plugins/log-cli/ looks like it does.

It's an HTML page, entirely generated by https://github.com/jenkins-infra/update-center2/ and it would be straightforward to pull in e.g. https://www.jenkins.io/template/ and fill it with content, so that it looks like it's properly part of the site.

I'd be happy to do the effort on update-center2, perhaps a plugin site contributor would be interested in designing the page contents? As a first iteration I'd be happy to just take the current content and wrap it in the page template, but something nicer may be worth some additional effort?

**Comment by zbynek** [comment]
Do you want to keep the current URL or could those be moved? (https://updates.jenkins.io/download/plugins/log-cli/ to the plugin site, https://updates.jenkins.io/download/war/ seems to be a duplicate of https://get.jenkins.io/war/ so maybe those could be merged). If moving is OK, the update center could just dump the information in JSON and the plugin site would process it (as a React component).

**Comment by daniel-beck** [comment]
Would keep the current URLs; it's important that it's effective immediately, otherwise that would negate recent improvements.

**Comment by zbynek** [comment]
Initial commit in https://github.com/jenkins-infra/update-center2/pull/469

**Comment by halkeye** [comment]
do we have all the data in plugin site? or can get it? I feel like it would make a great new tab like npm does.

**Comment by daniel-beck** [comment]
There's `plugin-versions.json` but it's very expensive to download (10+ MB IIRC), which is why it's not documented on the root page of https://updates.jenkins.io/

And, again, a big benefit of the current design is that new releases are visible immediately there. It's an easy way to start troubleshooting distribution.

**Comment by zbynek** [comment]
Well if the update center would export these as per-plugin JSON, the plugin site could fetch them from client side and render them nicely, there would also be no delay. That would remove the need to maintain frontend code (CSS, template substitution) in an otherwise backend repository, on the other hand the static HTMLs from the PR above could be used also pushed to the mirrors to make them look a bit nicer... not sure what's the best way forward 🤷

**Comment by halkeye** [comment]
We also can make the plugin site API check the etag and pull it if changes. There's lots of ways to handle it. I can update update center to split them.

My vote is keep the UI on plugin site.

**Comment by daniel-beck** [comment]
> maintain frontend code (CSS, template substitution) in an otherwise backend repository

If the plugin site didn't show me different information practically every time I reload the page, perhaps. I just don't trust it to act as a stable resource to determine which releases exist or which is the newest one, especially when I (in my admittedly unusual use case) need to be certain what's shown matches the current update center content exactly.

Given my use case, and given the update center is intended as a standalone component, I will move forward with my proposed solution. At a minimum, it should get all the low-tier "security researchers" off my back who keep reporting visible directory indexes as security vulnerabilities. If you want to replace the archives link on the plugins site with something different, feel free.

> could be used also pushed to the mirrors

If they're configured to render index.html as directory indexes, which they might not be. Additionally, has a problem when the index page is nontrivial, e.g. for the https://updates.jenkins.io/ index I was unable to use admonitions due to (IIRC) CORS.

**Comment by zbynek** [comment]
Well, we can have both. Finish https://github.com/jenkins-infra/update-center2/pull/469 now (mostly for distribution debugging purposes) and enhance the "Releases" tab in the future to also include download links (for Jenkins administrators).

**Comment by halkeye** [comment]
I'm going to close this as the new releases tab is powered by update center instead of github, it'll have all the download links baked in.
