### ISSUE TITLE
Can not download the archive 

### ISSUE THREAD

**Issue by quintinxuan** [jenkins-infra/plugin-site#464]
Can not download the archive 
https://updates.jenkins.io/download/plugins/javadoc/
https://get.jenkins.io/plugins/javadoc/1.6/javadoc.hpi

**Comment by halkeye** [comment]
There is an infra issue going on right now. People are working on it.

https://twitter.com/jenkinsci/status/1326994705230393344

**Comment by zbynek** [comment]
Though it's not resolved I suggest to close this as there are open duplicates in GitHub, e.g. https://github.com/jenkins-infra/jenkins.io/issues/3959
