### ISSUE TITLE
TestNG Results page - Add html tag in testng message

### ISSUE THREAD

**Issue by idan72** [jenkins-infra/plugin-site#465]
Hi,

I am running testng (version 1.15) from Jenkins.
I want to be able put newline inside the message.
I try to add "/n" or <br> but it just show as it and not make new line.
I try with this parameter "Escape exception messages?" checked and unchecked.

I also want in some cases add other html tags.

Can it be done and how ?

Thanks
--

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
