### ISSUE TITLE
Plugins Index page - Trending plugins are all library or API plugins

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site#468]
Problem with the [Plugins Index](https://plugins.jenkins.io) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/index.jsx)

## Screenshots 

![image](https://user-images.githubusercontent.com/21194782/99149246-b2aaab00-2684-11eb-98ff-9b85bff8fbcd.png)

## Possible Solution 

 

Ignore library and api plugins in trend?

**Comment by daniel-beck** [comment]
Would propose to ignore or deemphasize (handicap in the sport sense) trending plugins that are dependencies of _more popular_ plugins, as that hints at a newly added dependency elsewhere.

**Comment by zbynek** [comment]
It might be worth adding `api-plugin` label to 

```
ace-editor
momentjs
azure-sdk
caffeine-api
jjwt-api
snakeyaml-api
tuleap-api
bootstrap5-api
publish-over
pubsub-light
```

Query for checking
```
for(p of Object.values(JSON.parse(document.body.innerText).plugins)){p.dependencies.forEach(dep=>{if(p.popularity > 0.9 *(pl[dep.name]||{}).popularity && !dep.optional&&!pl[dep.name].labels.includes("api-plugin")){console.log(p.name,dep.name)}})}
```

**Comment by timja** [comment]
Could do but I checked a few of them and they are all labelled as 'library' plugins, probably mis-labelled and should be corrected? Any thoughts?

**Comment by daniel-beck** [comment]
> mis-labelled and should be corrected

"library" pre-dated "api-plugin" by many years, that's the wiki page label that was used. Not a single plugin used the "api-plugin" label.
