### ISSUE TITLE
JiraTestResultReporter page - TODO: Put a summary here

### ISSUE THREAD

**Issue by DanielDraus** [jenkins-infra/plugin-site#481]
Problem with the [JiraTestResultReporter](https://plugins.jenkins.io/JiraTestResultReporter) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

In hudson.model.FreeStyleProject:

Unable to add Jira ( 7.6 ) required fields.

Only Summary and Description avaliable.

## Screenshots 

 TODO: Add screenshots if possible 
![image](https://user-images.githubusercontent.com/26304182/99503206-54c8dc80-297e-11eb-8b56-db8fa405efdd.png)

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
