### ISSUE TITLE
Labelled Pipeline Steps page - TODO: Put a summary here

### ISSUE THREAD

**Issue by amershhadee** [jenkins-infra/plugin-site#495]
Problem with the [Labelled Pipeline Steps](https://plugins.jenkins.io/labelled-steps) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

labelledPowerShell + labelledBatch not exists when installed the plugin and can't use theme.

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
