### ISSUE TITLE
Jackson 2 API page - New release (2.12.0) references an incorrect URL, so the plugin can't be downloaded.

### ISSUE THREAD

**Issue by nateww** [jenkins-infra/plugin-site#508]
Problem with the [Jackson 2 API](https://plugins.jenkins.io/jackson2-api) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The plugin location is messed up

The new release from `https://updates.jenkins.io/current/update-center.json` references

` "url": "https://updates.jenkins.io/download/plugins/jackson2-api/2.12.0/jackson2-api.hpi",`

The URL (after a few redirects) eventually references:

- https://get.jenkins.io/plugins/jackson2-api/2.12.0/jackson2-api.hpi
- https://ftp-nyc.osuosl.org/pub/jenkins/plugins/jackson2-api/2.12.0/jackson2-api.hpi

However, that's an empty directory.

But, there appears to be an issue with a double directory, as the host has another sub-directory with an identical name.

https://ftp-nyc.osuosl.org/pub/jenkins/plugins/jackson2-api/2.12.0/2.12.0/

## Possible Solution 

Fix the mirror for the new release.

**Comment by halkeye** [comment]
oh awesome I'm glad i actually read this. I usually Assume the TODO: is someone wanting plugin support.

As for this actual bug, it is a problem in the site, but i think the data is upstream, so going to look into it more.

**Comment by nateww** [comment]
Thank you, and yes, I want plugin support in that I would like to access the plugin. ;)

**Comment by daniel-beck** [comment]
Seems to have resolved itself. I thought we killed off INFRA-160 with the fallback host :-(

**Comment by nateww** [comment]
Thank you, it's working for me as well.

**Comment by timja** [comment]
> Seems to have resolved itself. I thought we killed off INFRA-160 with the fallback host :-(

Since azure storage fell over we've been pointing fallback to OSU, there's a weird issue where directories are being duplicated on upload but then sorted later.

@olblak should we move back to using azure storage? it would fix this and the odd other issue?

**Comment by daniel-beck** [comment]
@timja Ah, I must have missed that this was still ongoing. Thanks!

**Comment by olblak** [comment]
> @olblak should we move back to using azure storage? it would fix this and the odd other issue?
I don't see why it would solve the issue as I don't see why it's currently broken but I'll revert those changes when I have enough time to dedicate to it
