### ISSUE TITLE
HTTP Request page - TODO: Jenkins' HTTP Request plugin does not wait until web page is loaded

### ISSUE THREAD

**Issue by Nilesh159** [jenkins-infra/plugin-site#509]
Problem with the [HTTP Request](https://plugins.jenkins.io/http_request) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Hi,
I am using the 'HTTP Request' plugin available in Jenkins. I have to do a GET request using this plugin. But the web page, I want to GET, takes a few seconds to load the page.
But, Jenkins completes the job and shows the 'loading' information in response.

Could someone please tell me how I can tell Jenkins to wait for a few seconds and then read the page and return the actual content of the web page?

Thanks in advance.

Regards,
Nilesh

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)

----

In regards to the actual issue I doubt that plugin can do it, and you'll need something that is DOM aware and can handle javascript, headless chrome perhaps?

**Comment by Nilesh159** [comment]
Thank you and sorry for inconvenience.
