### ISSUE TITLE
UiPath page - UiPath Run Tests : Java error java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by axelramirez21** [jenkins-infra/plugin-site#510]
Problem with the [UiPath](https://plugins.jenkins.io/uipath-automation-package) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Orchestrator 2020.10.3
Studio Pro version 2020.10.2
Jenkins 2.249.3

After the plugin runs successfully all the tests, I'm getting a "UiPath Run Tests" abort and a Java error java.lang.AbstractMethodError which is causing the activity to fail:

Running as SYSTEM
Building in workspace C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] Done
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/axelramirez21/uipath-jenkins-testsuite.git
 > git.exe init C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo # timeout=10
Fetching upstream changes from https://github.com/axelramirez21/uipath-jenkins-testsuite.git
 > git.exe --version # timeout=10
 > git --version # 'git version 2.29.1.windows.1'
 > git.exe fetch --tags --force --progress -- https://github.com/axelramirez21/uipath-jenkins-testsuite.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git.exe config remote.origin.url https://github.com/axelramirez21/uipath-jenkins-testsuite.git # timeout=10
 > git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
Checking out Revision c25104454b5d6e7628943cf9d17c3f6aa37dcc10 (refs/remotes/origin/master)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f c25104454b5d6e7628943cf9d17c3f6aa37dcc10 # timeout=10
Commit message: "Updated packages for testing"
 > git.exe rev-list --no-walk c25104454b5d6e7628943cf9d17c3f6aa37dcc10 # timeout=10
[Checks API] No suitable checks publisher found.
Expected plugin jar path on Jenkins master: C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\plugins\uipath-automation-package\WEB-INF\lib\uipath-automation-package.jar, extracting...
Extracting cli to temp folder C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp...done!
[net461] $ C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\cli-1.0.7573.25446\lib\net461\uipcli.exe run C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\uipcliargs1899444659949446558
Packing project at path C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo...
Step: Started
Step: StartCompilation
Step: FinishedCompilation
Step: StartBuild
Step: FinishedBuild
Step: StartSigning
Step: FinishedSigning
Step: Finished
Packaged project UiBank.Loan.Academy v1.0.42 saved to C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo\Output\jobs\Uipath-demo\builds\42
Expected plugin jar path on Jenkins master: C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\plugins\uipath-automation-package\WEB-INF\lib\uipath-automation-package.jar, extracting...
Extracting cli to temp folder C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp...done!
[net461] $ C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\cli-1.0.7573.25446\lib\net461\uipcli.exe run C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\uipcliargs5050568899471514996
Step: Started
Step: StartCompilation
Step: FinishedCompilation
Step: StartBuild
Step: FinishedBuild
Step: StartSigning
Step: FinishedSigning
Step: Finished
Packaged project UiBank.Loan.Academy v1.0.60558615-alpha saved to C:\Users\Administrator\AppData\Local\Temp\f5dc030f748246d3b2cd63a26b7cd195
Deploying project(s) UiBank.Loan.Academy.1.0.60558615-alpha to https://ec2amaz-sdv4r1j.rpauniverse.com/ and tenant Default...
Deployed UiBank.Loan.Academy to organization unit Default.
Running tests in set  on https://ec2amaz-sdv4r1j.rpauniverse.com/ (tenant Default)...
Starting test set Jenkins_2020-12-01T21:50:18.1382758Z_UiBank Loan Academy_Tests_1.0.60558615-alpha ...
Started test set Jenkins_2020-12-01T21:50:18.1382758Z_UiBank Loan Academy_Tests_1.0.60558615-alpha with execution id 26
Running tests... 0 passed, 0 failed or canceled, 7 total. Waiting for 20s.
Running tests... 2 passed, 0 failed or canceled, 7 total. Waiting for 20s.
Running tests... 4 passed, 0 failed or canceled, 7 total. Waiting for 20s.
Running tests... 6 passed, 0 failed or canceled, 7 total. Waiting for 20s.
Running tests... 7 passed, 0 failed or canceled, 7 total. Waiting for 20s.
Finished running test set 'Jenkins_2020-12-01T21:50:18.1382758Z_UiBank Loan Academy_Tests_1.0.60558615-alpha' ...
Writing test results of type junit to C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo\Output\jobs\Uipath-demo\builds\42\tests\Result.xml
Recording test results
ERROR: Step ‘UiPath Run tests’ aborted due to exception: 
java.lang.AbstractMethodError: Method com/uipath/uipathpackage/UiPathTest.getChecksName()Ljava/lang/String; is abstract
	at com.uipath.uipathpackage.UiPathTest.getChecksName(UiPathTest.java)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:189)
	at com.uipath.uipathpackage.UiPathTest.publishTestResults(UiPathTest.java:265)
	at com.uipath.uipathpackage.UiPathTest.perform(UiPathTest.java:157)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1919)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Expected plugin jar path on Jenkins master: C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\plugins\uipath-automation-package\WEB-INF\lib\uipath-automation-package.jar, extracting...
Extracting cli to temp folder C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp...done!
[net461] $ C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\cli-1.0.7573.25446\lib\net461\uipcli.exe run C:\Users\Administrator\AppData\Local\Jenkins\.jenkins\workspace\Uipath-demo@tmp\uipcliargs6175992011952345984
Deploying project(s) UiBank.Loan.Academy.1.0.42 to https://ec2amaz-sdv4r1j.rpauniverse.com/ and tenant Default...
Deployed UiBank.Loan.Academy to organization unit Default.
[Checks API] No suitable checks publisher found.
Finished: FAILURE

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 
N/A

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
