### ISSUE TITLE
Bitbucket Pipeline for Blue Ocean page - Invalid link

### ISSUE THREAD

**Issue by strpeter** [jenkins-infra/plugin-site#520]
Problem with the [Bitbucket Pipeline for Blue Ocean](https://plugins.jenkins.io/blueocean-bitbucket-pipeline) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The reference to the corresponding Github project is invalid.

## Screenshots 

![image](https://user-images.githubusercontent.com/2798595/101622914-f2f91100-3a17-11eb-8b3a-6b789010726b.png)

## Possible Solution 

Add a valid Github link, e.g. https://github.com/jenkinsci/blueocean-plugin/

**Comment by halkeye** [comment]
Your absolutely right. Its a problem upstream with multi module plugins. 

In this case blueocean repo contains most of the plugins but I'll leave this open.
