### ISSUE TITLE
HTTP Request page - TODO: Put a summary here

### ISSUE THREAD

**Issue by pmyakishev** [jenkins-infra/plugin-site#521]
Problem with the [HTTP Request](https://plugins.jenkins.io/http_request) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 
Could you update the documentation? it seems to be old. thx
## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
