### ISSUE TITLE
docker-build-step page - TODO: Buildcontext is not correct when using a Dockerfile from different directory

### ISSUE THREAD

**Issue by rsam70** [jenkins-infra/plugin-site#543]
Problem with the [docker-build-step](https://plugins.jenkins.io/docker-build-step) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 

## Screenshots 

Project folder consists of 
data
   \ project1
   \ project2 
   Dockerfile

some of these projects  have reference to each other
So Dockerfile consist of

COPY project1/proj  ...
COPY project2/proj  ...

Provided 
Build context folder: $WORKSPACE/data

if Dockerfile at Data\Dockerfile the container is created.

If Docker file at Data\Project1\Dockerfile 

these references from Dockerfile are not found

COPY project1/project1.csproj

Generate error they are not found.

[Docker] ERROR: Failed to create docker image: Could not build image: COPY failed: stat /var/lib/docker/tmp/docker-builder225649340/Project1/Project1.csproj: no such file or directory
ERROR: Build step failed with exception
com.github.dockerjava.api.exception.DockerClientException: Could not build image: COPY failed: stat /var/lib/docker/tmp/docker-builder225649340/Project1/Project1.csproj,: no such file or directory

## Possible Solution 

Verified locally that docker build correctly finishes in both situation.
1) either from Data\Dockerfile
2) or from Data\Project1\Dockerfile

Buildcontext fixed to Data.

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)

**Comment by rsam70** [comment]
Ah yes. Indeed

Thank you!.
