### ISSUE TITLE
database page - Padding under page switcher looks off

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site#545]
Problem with the [database](https://plugins.jenkins.io/database) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

## Screenshots 

![image](https://user-images.githubusercontent.com/21194782/102987582-792e5080-450a-11eb-88aa-e3591c453871.png)

Contrasted with NPM which looks better:
https://www.npmjs.com/package/@backstage/create-app

![image](https://user-images.githubusercontent.com/21194782/102987605-83e8e580-450a-11eb-8110-2ada821f3a3d.png)

## Possible Solution 

 

N/A

**Comment by halkeye** [comment]
this was apparently fixed in #561

**Comment by timja** [comment]
ah nice looks much better than the screen shot
