### ISSUE TITLE
jira-ext page -Plugin is not working with latest versions of Jenkins

### ISSUE THREAD

**Issue by nagarameshreddy** [jenkins-infra/plugin-site#546]
Problem with the [jira-ext](https://plugins.jenkins.io/jira-ext) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 

## Screenshots 

![image](https://user-images.githubusercontent.com/28221547/103336012-d5f6b180-4a9c-11eb-8a4c-48dcd2b9776b.png)

Even ticket exists its giving error ticket not found

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
