### ISSUE TITLE
GCP Secrets Manager Credentials Provider page - TODO: Put a summary here

### ISSUE THREAD

**Issue by andycockers** [jenkins-infra/plugin-site#558]
Problem with the [GCP Secrets Manager Credentials Provider](https://plugins.jenkins.io/gcp-secrets-manager-credentials-provider) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

I am running Jenkins in Kubernetes outside of GCP. I can't get the plugin to connect to my GCP project. I have the env var "GOOGLE_APPLICATION_CREDENTIALS" set in my kubectl yaml file and also in the Jenkins env var section, pointing at a valid service account key.

Error message is Jenkins logs:

Could not retrieve the credentials from GCP Secrets Manager
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
