### ISSUE TITLE
Allure page -  plugin documentation page link is not working

### ISSUE THREAD

**Issue by LivingBrain** [jenkins-infra/plugin-site#560]
Problem with the [Allure](https://plugins.jenkins.io/allure-jenkins-plugin) page, 

**Plugin documentation page** link is not working

https://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin - **404**

**Comment by oleg-nenashev** [comment]
CC @eroshenkoam

**Comment by halkeye** [comment]
I'm very tempted to close this one as its not an actual issue with the plugin site, but the data provided by the allure plugin.

**Comment by zbynek** [comment]
This should be tackled in the Allure plugin repo, see https://github.com/jenkinsci/allure-plugin/pull/289
