### ISSUE TITLE
Extended Choice Parameter page - TODO: issue with jenkins 2.235

### ISSUE THREAD

**Issue by inzagod** [jenkins-infra/plugin-site#562]
Problem with the [Extended Choice Parameter](https://plugins.jenkins.io/extended-choice-parameter) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

version of the plugin : the latest 0.82

hi,
after upgrading  jenkins on openshift platform (version 2.235-5)
i encountered an issue with a pipeline that contains extended choice parameter groovy script as you can see in joined file.
ECP-groovy-script.txt
before upgrade everything worked fine and the version of the plugin was 0.78 and jenkins version was 2.176
do you think the problem is the groovy script ?
i tested to revert to 0.78 but jenkins 2.235.5 does not support this version, i received an error when i opened the pipeline

thanks a lot 
ludo

please joined 2 screenshots : before and after upgrade display (in several web browser)

![before_upgrade](https://user-images.githubusercontent.com/42611540/105056962-0a92d300-5a75-11eb-973d-215d79a82e0f.png)

![after_upgrade](https://user-images.githubusercontent.com/42611540/105057859-eedbfc80-5a75-11eb-9e77-af26723e3ac7.png)

[ECP_script.txt](https://github.com/jenkins-infra/plugin-site/files/5836906/ECP_script.txt)

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)

**Comment by inzagod** [comment]
thanks a lot for your reply
it is a bug yes
the joined script worked fine with 0.78 version but in 0.82 not

thank you
ludo
