### ISSUE TITLE
Role-based Authorization Strategy page - Cannot assign role to users

### ISSUE THREAD

**Issue by vasanthy2k7** [jenkins-infra/plugin-site#563]
Problem with the [Role-based Authorization Strategy](https://plugins.jenkins.io/role-strategy) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

I have tried to add user to roles in Assign Role page, but it won't add and not showing any error. i am using latest plugin (version 3.1)

## Screenshots 
![image](https://user-images.githubusercontent.com/77719388/105143463-e7722d00-5b21-11eb-935f-5c76be1c76d2.png)

Please fix this issue and thanks in advance

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)

fyi @oleg-nenashev @res0nance
