### ISSUE TITLE
GCP Secrets Manager Credentials Provider page - How does this work with Kubernetes

### ISSUE THREAD

**Issue by andycockers** [jenkins-infra/plugin-site#564]
Problem with the [GCP Secrets Manager Credentials Provider](https://plugins.jenkins.io/gcp-secrets-manager-credentials-provider) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Hi folks,

I'm trying to use the gcp secrets manager plugin with Jenkins in a Kubernetes instance outside of GCP.

I've installed the plugin, copied a service account with the right permissions to a location that Jenkins can 'see' and set the environment variable in Jenkins AND at container level in helm yaml. However, when I try to access GCP secrets via the Jenkins UI, I get the following error in the log:

Could not retrieve the credentials from GCP Secrets Manager
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
