### ISSUE TITLE
ThinBackup page - TODO: Documentation link on "plugins.jenkins.io" doesn't work

### ISSUE THREAD

**Issue by bassani2014** [jenkins-infra/plugin-site#575]
Selecting the documentation link on https://plugins.jenkins.io/thinBackup/#documentation points to an invalid page.

Actual: Link points to https://github.com/jenkinsci/think-backup-plugin (Note "think" in the url)

Expected: Should point to https://github.com/jenkinsci/thin-backup-plugin

**Comment by timja** [comment]
There's a PR open to fix this: https://github.com/jenkinsci/thin-backup-plugin/pull/25/files

as this is an issue with a plugin and not the plugin site itself I'm going to close this issue.

Thanks for the report
