### ISSUE TITLE
GitLab plugin: the latest stable version not available on plugins.jenkins.io

### ISSUE THREAD

**Issue by sadok-f** [jenkins-infra/plugin-site#576]
Problem with the [GitLab](https://plugins.jenkins.io/gitlab-plugin) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

The latest stable version for Gitlab-plugin (`1.5.17`) not available on  plugins.jenkins.io, currenlty only `1.5.13` is available and it has some bugs.

## Possible Solution 

Update plugins.jenkins.io with the latest version from gitlab-plugin: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.17

Thank you

**Comment by halkeye** [comment]
Hrm.. thats interesting. Either the update job isn't running (i see 2021-02-10T18:03:48.000Z on the bottom, so i think its good) or that update center wasn't updated with the release.

Are you the mainatiner?

**Comment by halkeye** [comment]
https://updates.jenkins.io/current/plugin-versions.json only has 1.5.13, so @daniel-beck (update center) or @markyjackson-taulia (gitlab plugin). I'm guessing markey didn't actually publish to update center?

**Comment by sadok-f** [comment]
thank you for your reply, no I'm not the maintainer.
Markey cannot maintain anymore the repo and he is putting the plugin for adoption:
https://github.com/jenkinsci/gitlab-plugin/discussions/1098

**Comment by halkeye** [comment]
Yea, its not made it to update center, so something went wrong with the release. Plugin site uses update center as the source of info.

```
 ☎  ~  …  digitalocean-plugin  master  2✎  2+  %    curl -qLs 'https://updates.jenkins.io/update-center.actual.json' | jq '.plugins."gitlab-plugin"'
{
  "buildDate": "Sep 12, 2019",
  "compatibleSinceVersion": "1.4.0",
  "dependencies": [
    {
      "name": "matrix-project",
      "optional": false,
      "version": "1.10"
    },
    {
      "name": "plain-credentials",
      "optional": true,
      "version": "1.1"
    },
    {
      "name": "git-client",
      "optional": false,
      "version": "1.19.0"
    },
    {
      "name": "workflow-step-api",
      "optional": false,
      "version": "2.16"
    },
    {
      "name": "workflow-job",
      "optional": false,
      "version": "1.15"
    },
    {
      "name": "credentials",
      "optional": false,
      "version": "2.1.0"
    },
    {
      "name": "git",
      "optional": false,
      "version": "2.4.1"
    },
    {
      "name": "display-url-api",
      "optional": false,
      "version": "1.1.1"
    }
  ],
  "developers": [
    {
      "developerId": "markyjackson-taulia",
      "email": "marky.r.jackson@gmail.com",
      "name": "Marky Jackson"
    }
  ],
  "excerpt": "This plugin allows <a href=\"http://gitlab.com/\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">GitLab</a> to trigger Jenkins builds and display their results in the GitLab UI.",
  "gav": "org.jenkins-ci.plugins:gitlab-plugin:1.5.13",
  "labels": [
    "trigger"
  ],
  "name": "gitlab-plugin",
  "popularity": 51474,
  "previousTimestamp": "2019-04-17T11:59:34.00Z",
  "previousVersion": "1.5.12",
  "releaseTimestamp": "2019-09-12T05:01:28.00Z",
  "requiredCore": "1.609.3",
  "scm": "https://github.com/jenkinsci/gitlab-plugin",
  "sha1": "a7r9vfNtTXN1mYhx0ShEQ0LJnCM=",
  "sha256": "toOI7LnTA0ZKWLs+LYfqfP+0fPZXdQJpM2FUXBPrWy0=",
  "title": "GitLab",
  "url": "https://updates.jenkins.io/download/plugins/gitlab-plugin/1.5.13/gitlab-plugin.hpi",
  "version": "1.5.13",
  "wiki": "https://plugins.jenkins.io/gitlab-plugin"
}
```

**Comment by timja** [comment]
I’m going to close this as it’s nothing to do with the plugin site, as linked above this plugin needs a new maintainer to publish a release

**Comment by daniel-beck** [comment]
GitLab plugin 1.5.17 has never been properly released, only a snapshot (two, actually, Jan 15 '20 and Oct 7 '20) exists in Artifactory. This usually happens when maintainers don't follow our documentation on how to release things.
