### ISSUE TITLE
Unalignment of graphs in Version 1.13

### ISSUE THREAD

**Issue by TToliver** [jenkins-infra/plugin-site#578]
Problem with the [Yet Another Build Visualizer](https://plugins.jenkins.io/yet-another-build-visualizer) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Since version 1.13 we are noticing some unalignment in the graphs. Several of the jobs get pushed to the left side. 

## Screenshots 

![image](https://user-images.githubusercontent.com/49394909/107960558-16ef4a80-6fa5-11eb-90fe-c4513969d423.png)

**Comment by oleg-nenashev** [comment]
Hello. GitHub Issues in this repository are for the plugin site only. Please report plugin issues in the respective issue tracker: https://issues.jenkins.io/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20yet-another-build-visualizer-plugin .
