### ISSUE TITLE
Role-based Authorization Strategy page - TODO: Put a summary here

### ISSUE THREAD

**Issue by techguane** [jenkins-infra/plugin-site#579]
Problem with the [Role-based Authorization Strategy](https://plugins.jenkins.io/role-strategy) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by techguane** [comment]
After wanting to install+restart this plugin in my Jenkins 2.263.3 (running in a docker container in Linux ubuntu 20.04), a login screen is not accessible any longer and it defaults to display the error screen shown in the attached image. I have stop/start as well as removed/reinstall the docker container twice with no correction. Any known bug-fixes for this one out yet?

![Screen Shot 2021-02-17 at 3 12 59 PM](https://user-images.githubusercontent.com/6108133/108281701-3a092e00-714e-11eb-8288-89922035a9b5.png)

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
