### ISSUE TITLE
Jira page - TODO:  Jira Software 8.14.0 data center version does not work together in an integrated manner

### ISSUE THREAD

**Issue by burakbal751** [jenkins-infra/plugin-site#582]
Problem with the [Jira](https://plugins.jenkins.io/jira) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: We updating our server Jira to Jira Data Center. But we have a problem. When we looked the logs, we realized that's about the Jenkins connection. Don't you support integration with the Jira Datacenter version ? Can you help us ? We are in live and we have to solve this problem critically. 

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
