### ISSUE TITLE
Pagination limit in plugins.jenkins.io

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/plugin-site#585]
With this request: https://plugins.jenkins.io/ui/search?sort=installed&categories=&labels=&view=Tiles&page=50&query= I got only the first 1000 plugins, lacking the tail of ~800.

This is particularly useful for people looking for low-popularity plugins, which are no longer displayed on the page. This behavior seemed to work even some weeks ago.

**Comment by halkeye** [comment]
Yea there's a couple minor bugs with the algoila implementation. 
Debugging your issues I noticed I never hooked up the sorting radios either.

The limit of 1000 is a setting. I've bumped the limit 2000 on #588 

I think #586 fixes this but you still won't be able to sort by installs.

Maybe in the mean time we should have algolia for default search, and then the other options fall back to the plugin-site-api for now. What do you think @MarkEWaite

**Comment by MarkEWaite** [comment]
Agreed that Algolia should be default search @halkeye

**Comment by halkeye** [comment]
closing in favor of #632 since the original reported pagination issue has now been fixed.
