### ISSUE TITLE
JS error "Invalid array length"

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/plugin-site#586]
This request for example: https://plugins.jenkins.io/ui/search/?sort=installed&categories=&labels=ui&view=Tiles&page=50&query= leads to a regular page to load, then JS magic happened and the page becomes blank.

```
RangeError: Invalid array length
    at t.a.pageRange (Pages.jsx:21)
    at t.a.render (Pages.jsx:42)
[...]
```

Easy to reproduce, just look for any plugin, use the last page (50), then click on a category on the left => blank page.
This is not problematic with "Android development" but is with "List view column plugins", so it seems the code is buggy ;)

**Comment by halkeye** [comment]
Thats so weird. It doesn't break at all in dev mode. I'm going to have to dig into this.

**Comment by halkeye** [comment]
Okay, tracked it down. It based on the original plugin site's pagination system. I replaced it with a module that handles it and edge cases way better.

I have a PR ready
