### ISSUE TITLE
Active Choices page - Radio Button and Check Boxes are not working in active choice in version plugin 2.5.3 and Jenkins 2.281

### ISSUE THREAD

**Issue by xs2bharat** [jenkins-infra/plugin-site#587]
Problem with the [Active Choices](https://plugins.jenkins.io/uno-choice) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Actual - Radio Button and Check Boxes are not working in active choice in version plugin 2.5.3 and Jenkins 2.281
Getting Error 
Error executing script for dynamic parameter
java.lang.RuntimeException: Return type of Groovy script must be a valid String, List, or Map

Expected - Active choice parameters should populate correctly as per configuration.

**Comment by MarkEWaite** [comment]
@xs2bharat this GitHub issues page is for the components that provide the Jenkins plugins site.  It is not for bug reports about specific plugins.

Submit reports for specific plugins to the [Jenkins issue tracker](https://issues.jenkins.io/) by following the directions at ["How to report an issue"](https://www.jenkins.io/participate/report-issue/).
