### ISSUE TITLE
The drop-down box does not take effect

### ISSUE THREAD

**Issue by immortal-ziyang** [jenkins-infra/plugin-site#605]
If the parameter type is a drop-down box, when using the Rebuild plugin to rebuild, the drop-down box will become an input box. What caused this?

**Comment by halkeye** [comment]
Hi, 

As you didn't include any information as to which page on the plugin site this affects, I'm thinking your request is about a plugin.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)

**Comment by immortal-ziyang** [comment]
Hi,

Yes, it is the problem caused by my use of rebuild-plugin, I want to solve this problem, but I don't know who to contact
