### ISSUE TITLE
Search 'scm plugins' returns only 2 results

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#606]
Similar issue to earlier issue with the word 'plugin'.  If I drop the word 'plugins' and only search for 'scm', 31 results are returned.

**Comment by MarkEWaite** [comment]
Closed by #607

**Comment by MarkEWaite** [comment]
Oops, #607 has not yet merged...

**Comment by halkeye** [comment]
Oops missed one in my merge a thon last night
