### ISSUE TITLE
Plugin site is importing the jenkins.io algolia config for the search box

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#612]
search box was filtered out on #611 but not the script tags that go with it

Probably something like (untested) needs to be added to utils.js:
```
jQuery('script[href*="algolia")').remove()
jQuery('script:contains(docsearch)').remove()
```

**Comment by zbynek** [comment]
Fixed in https://github.com/jenkins-infra/plugin-site/commit/bde31274f5df87eaccf881c35b6d0e04a3692c6f
