### ISSUE TITLE
Problem with Jenkins Credentials: OSF Two Factor Auth Credentials

### ISSUE THREAD

**Issue by paramosr** [jenkins-infra/plugin-site#613]
Problem with the [OSF Builder Suite For Salesforce Commerce Cloud :: Deploy](https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

 
I'm triying to use this plugin to deploy code to Staging, which needs the two factor authentication. I am doing the deployment through jenkins, where to store the OSF keys I use the types corresponding to the certificates to store. The problem comes when I try to store the two facto certificate. I find with 3 text type fields (Server Certificate, Client Certificate and Client Private Key) in which I can not indicate the certificates and keys previously created. How to indicate in these text type inboxes the certificates and keys?

## Screenshots 

 TODO: Add screenshots if possible 
![image](https://user-images.githubusercontent.com/60689893/111504753-40d49200-8748-11eb-863f-44d101612921.png)
![image](https://user-images.githubusercontent.com/60689893/111504930-619ce780-8748-11eb-90df-53b736492534.png)

## Possible Solution 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
