### ISSUE TITLE
Unable to send a message to a slack channel using 'blocks' parameter of the slackSend method from Jenkinsfile

### ISSUE THREAD

**Issue by puneet-kr-sh** [jenkins-infra/plugin-site#614]
I have generated a very simple block at https://app.slack.com/block-kit-builder/ & trying to send this from my Jenkensfile as follows : 

script{
                slackSend(
                    channel: "xxxxxx",
                    teamDomain: 'xxxxxx',
                    tokenCredentialId: 'xxxxxx-xxxxx-xxx-xxxx',
                    blocks: [
                    		{
                    			type: "section",
                    			text: {
                    				type: "mrkdwn",
                    				text: "New Paid Time Off request from <example.com|Fred Enriquez>\n\n<https://example.com|View request>"
                    			}
                    		}
	                    ]
	           )
            }

But this throws the below err 
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 57: **_unexpected token: section_** @ line 57, column 30.
                       			type: "section",

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
