### ISSUE TITLE
Confluence Publisher page - TODO: Getting error because basic user authentication is disabled on confluence

### ISSUE THREAD

**Issue by vilasd** [jenkins-infra/plugin-site#625]
Problem with the [Confluence Publisher](https://plugins.jenkins.io/confluence-publisher) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Confluence publisher plugin does not allow token based authentication

## Screenshots 

 TODO: Add screenshots if possible 
![Screen Shot 2021-04-01 at 12 41 51 PM](https://user-images.githubusercontent.com/14971467/113345800-d09d4300-92e7-11eb-9e1a-ebce3f74bc0a.png)

## Possible Solution 

 

N/A

**Comment by halkeye** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)
