### ISSUE TITLE
Remove Non Algoila support

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#631]
* [ ] Document how to connect agolia for personal development
* [ ] Remove code accessing plugin-site-api endpoint

**Comment by RiyaGupta89** [comment]
@halkeye Can I work on this issue? And please could you elaborate more that what needs to be done in this issue?

**Comment by halkeye** [comment]
Its been a year so i'm fuzzy, but essentially for the second item there's a branching path - https://github.com/jenkins-infra/plugin-site/blob/bee6111f42969f096728056928b6d8a0af448b17/src/templates/search.jsx#L40-L90 - that uses the /api instead of algolia. Its safe to delete now.

For the first item, @zbynek might be able to give better pointers, essentially a quickstart on how to setup your own free algolia account and the right env variables.

You can work on any of the issues you want, but i don't want to assign multiple to a single person until one gets done.

**Comment by RiyaGupta89** [comment]
@halkeye Sure. I will first complete my previously assigned issue and will ask to work on this one.

**Comment by krisstern** [comment]
Hi, I would like to work on this issue.

**Comment by halkeye** [comment]
Sounds good. Assigned

**Comment by krisstern** [comment]
Thanks @halkeye Will follow up with a PR soon.

**Comment by krisstern** [comment]
@halkeye Just wanted to confirm that I am supposed to remove the `else` part? I.e. https://github.com/jenkins-infra/plugin-site/blob/1031d57d35ddc738228485d6173a9b50a67d66dd/plugins/plugin-site/src/templates/search.jsx#L74-L97

This is the else part that calls the Gatsby API.
