### ISSUE TITLE
ruby-runtime page - TODO: Put a summary here

### ISSUE THREAD

**Issue by bajajamit09** [jenkins-infra/plugin-site#634]
Problem with the [ruby-runtime](https://plugins.jenkins.io/ruby-runtime) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 

## Screenshots 

 TODO: Add screenshots if possible 

## Possible Solution 

 
This plugin does not support Java-11. 
N/A

**Comment by bajajamit09** [comment]
ubi images are installed with jav11 and unable to use this plugin.

**Comment by timja** [comment]
We're about to stop shipping ruby run time at all
https://github.com/jenkins-infra/jenkins.io/blob/halkeye-patch-1/content/blog/2021/04/2021-04-16-deprecated-ruby-runtime.adoc

(https://github.com/jenkins-infra/jenkins.io/pull/4256)
