### ISSUE TITLE
Plugin page not found page - TODO: TFS Plugin Page

### ISSUE THREAD

**Issue by vishalgoyal16444** [jenkins-infra/plugin-site#668]
Problem with the [Plugin page not found](https://plugins.jenkins.io) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/pages/404.jsx)

TODO: Microsoft and Jenkins documentation refers to this page for plugin between Jenkins and Azure DevOps Server 
https://plugins.jenkins.io/tfs/

## Screenshots 
<img width="879" alt="PageNotFound" src="https://user-images.githubusercontent.com/73927117/117433138-c73b7200-af48-11eb-9c64-00e70eb230dd.png">

## Possible Solution 

 

N/A

**Comment by timja** [comment]
It was suspended in https://issues.jenkins.io/browse/INFRA-2751?focusedCommentId=407049&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-407049

License issue is fixed, but needs a security issue fixed before it will be restored
