### ISSUE TITLE
Android Emulator page - Emulator getting started on master instance and hence failing (after upgrade to 3.1.2)

### ISSUE THREAD

**Issue by abhinavaditya777** [jenkins-infra/plugin-site#716]
Problem with the [Android Emulator](https://plugins.jenkins.io/android-emulator) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

TODO: Describe the expected and actual behavior here 

I upgraded the instance to 2.277.4 and also updated different plugins. We use one plugin called Android Emulator plugin which launches Android emulator to run tests on the same. However, after plugin upgrade while launching emulator it is always searching the avd in Jenkins master instance and not on the agent node. Hence, the emulator do not get launched and build fails.

Logs: 

[EnvInject] - Variables injected successfully.
17:14:56 [android] Using Android SDK: /Users/lrandroid/Library/Android/sdk
17:14:56 [android] Cannot start Android emulator: Could not start AVD 'lra_devtest_performance', as it could not be found at '/apps/home/jnknsprd/.android/avd/lra_devtest_performance.avd'
17:14:56 [PostBuildScript] - [INFO] Executing post build scripts.
17:14:56 [PostBuildScript] - [INFO] Build does not have any of the results [SUCCESS]. Did not execute build step #0.

The AVD is present in $HOME/.android/avd 

## Possible Solution 

 

N/A

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
