### ISSUE TITLE
ec2 snippet generated by Pipeline Snippet Generator fails in pipeline

### ISSUE THREAD

**Issue by jhilburnsds** [jenkins-infra/plugin-site#717]
Problem with the [Amazon EC2](https://plugins.jenkins.io/ec2) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

When executing the EC2 plugin from within a pipeline project, an error is returned when attempting to locate the template. Example: 

```
java.lang.IllegalArgumentException: Error in AWS Cloud. Please review AWS template defined in Jenkins configuration.
	at hudson.plugins.ec2.EC2Step$Execution.run(EC2Step.java:155)
	at hudson.plugins.ec2.EC2Step$Execution.run(EC2Step.java:125)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

The call that returned the above code used the following format:

    ec2 cloud: 'Automation-Cloud', template: 'automation-client'

As can be seen from the attached screenshot, this is the command provided by the Pipeline Snipper Generator.

'Automation-Cloud' is a cloud created in Jenkins and 'automation-client' is the label applied to instances created within that cloud. 

Examining the code, it appears that hudson.plugins.ec2.EC2Cloud.getTemplate(String) method is searching for templates by Description rather than Labels. This results in calls such as the following being required:

    ec2 cloud: 'Automation-Cloud', template: 'AWS Amazon Linux AMI 2'

It appears that either the code generated by the Snippet Generator is incorrect or the command itself is not searching as it should. In either case, this appears to be a bug.

## Screenshots 

![image](https://user-images.githubusercontent.com/85713196/121608653-4835cf80-ca07-11eb-9913-6b9faad19613.png)

## Possible Solution 

 

If hudson.plugins.ec2.EC2Cloud.getTemplate(String template) is unable to find a template whose description matches the provided string, it should check to see if a template with matching label exists and return based on that match if so.

Or the snippet generation should be fixed to generate a correct snippet.

**Comment by timja** [comment]
Hi, 

Thank you very much for the report, but the issue tracker for the plugins.jenkins.io site is used to track issues with the plugin site itself. Your request seems to be a request for help, not a report of a functionality issue or improvement.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins-ci.org)
