### ISSUE TITLE
Warnings regex is incorrectly applied, leading to false positive security warnings

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#751]
https://github.com/jenkins-infra/plugin-site/blob/2b7b2e361b5dbbd41e60c0ef67edd717105751c1/plugins/gatsby-source-jenkinsplugins/utils.js#L186 tries to match the intended "matching" behavior by wrapping the regex in `^` and `$`.

This leads to a wrong result on https://plugins.jenkins.io/kubernetes/ with regexes like https://github.com/jenkins-infra/update-center2/blob/345c6f88f14e5254857fd1128881264e12895611/resources/warnings.json#L9318

I think a "proper" hack is to wrap the entire thing in `(…)` (below), but ideally there's a better way to match.

```
 warning.active = !!warning.versions.find(version => plugin.version.match(`^(${version.pattern})$`));

**Comment by zbynek** [comment]
@daniel-beck thanks! I don't think there is a better way to do that in JS than your suggestion.
