### ISSUE TITLE
Changelog -  no version 2.282

### ISSUE THREAD

**Issue by woberle** [jenkins-infra/plugin-site#757]
Problem with the "SSH Credentials" plugin.

TODO: The documentation for the plugin lists "Requires Jenkins 2.282". On https://www.jenkins.io/changelog-stable/, there is no version 2.282.

**Comment by zbynek** [comment]
2.282 is a weekly release: https://www.jenkins.io/changelog/, the changelog you mentioned is for [long term support (LTS) version](https://www.jenkins.io/download/lts/)

Plugins compatible with 2.282 run on all newer versions of Jenkins, including LTS 2.289.1 and 2.289.2

**Comment by halkeye** [comment]
A plugin author can depend on whatever version they want. That's the
minimum version though. So you can go higher.

2.282 is a weekly not a stable. https://www.jenkins.io/changelog/

Feel free to pick a higher stable
