### ISSUE TITLE
feature request: Run s/slave/node/g on all plugin name/docs/content/etc before outputting

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#811]
there's a bunch of really old plugins that still mention slave - https://plugins.jenkins.io/ui/search/?labels=monitoring
There's really no reason we can't do some search and replacing before rendering.

**Comment by zbynek** [comment]
Simple replace in docs content may result in docs no longer describing UI properly (checkbox with "slave" in UI described as "agent"), one also has to be careful about code snippets etc.

For plugin title and excerpt (=content of index.jelly) it should be safe to do, but that would need to be done in `update-center2` repo to have the same plugin names in Jenkins UI and plugin site.

In general it would be good to just remove some of the old plugins from distribution and file PRs for the ones that are still actively maintained. I tried https://github.com/jenkinsci/splunk-devops-plugin/pull/25 , https://github.com/jenkinsci/scriptler-plugin/pull/55, https://github.com/jenkinsci/proxmox-plugin/pull/21, https://github.com/jenkinsci/mac-plugin/pull/28 so far.

@dheerajodha it might be cool to add a probe for up-to-date terminology into the health score.

**Comment by halkeye** [comment]
Yea I don't really like the idea, but wanted to throw it up so its noted down.

**Comment by zbynek** [comment]
> Yea I don't really like the idea,

OK, then I'm closing this for now and let's reopen it if needed.
