### ISSUE TITLE
autonomiq page - plugins docs no longer inline

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#828]
Problem with the [autonomiq](https://plugins.jenkins.io/autonomiq) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Previously, a `url` entry in the plugin pom like https://github.com/jenkinsci/autonomiq would cause the README file at the root of the GitHub repository to be used as documentation and the content would be inserted inline.  That seems to have changed so that the README at the root is not inserted inline but is a hyperlink.

The full `url` as used by the git plugin still inserts the documentation inline.

## Screenshots 

![image](https://user-images.githubusercontent.com/156685/137553924-a44b35c7-258f-45e7-809c-f05dcf236d1c.png)

## Possible Solution 

N/A

**Comment by halkeye** [comment]
https://plugins.jenkins.io/api/plugin/autonomiq/
"wiki":{"content":"<div>\n Documentation for this plugin is here: \n <a href=\"https://github.com/jenkinsci/autonomiq-plugin\">https://github.com/jenkinsci/autonomiq-plugin</a>\n</div>","url":"https://github.com/jenkinsci/autonomiq-plugin"}

I don't have VPN on this computer to check the logs in loki. And plugin-site-api doesn't record error accessing docs to sentry (since there's soooooo much bad data)

**Comment by halkeye** [comment]
17:36:13.515 [qtp1041152279-18] DEBUG i.j.plugins.services.impl.HttpClient - https://api.github.com/repos/jenkinsci/autonomiq-plugin/readme?ref=master: X-GitHub-Media-Type: github.v3; param=html
17:36:13.516 [qtp1041152279-18] DEBUG i.j.plugins.services.impl.HttpClient - https://api.github.com/repos/jenkinsci/autonomiq-plugin/readme?ref=master: X-GitHub-Request-Id: BB80:23BE:1488EFD:28043FC:616A1E7D
17:36:13.516 [qtp1041152279-18] WARN  i.j.plugins.services.impl.HttpClient - Unable to get content from https://api.github.com/repos/jenkinsci/autonomiq-plugin/readme?ref=master - returned status code 404

**Comment by halkeye** [comment]
curl -qs 'https://updates.jenkins.io/current/update-center.actual.json' | jq '.plugins["autonomiq"].defaultBranch'
null

curl -qs 'https://updates.jenkins.io/current/update-center.actual.json' | jq '.plugins["configuration-as-code"].defaultBranch'
"master"

Not sure whats going on there.

**Comment by halkeye** [comment]
https://github.com/jenkinsci/autonomiq-plugin/blob/main/pom.xml#L104 <-- i think its the capital letters. The code that loops through all the repos can't find a match. So update center doesn't output a default branch. So plugin site doesn't know how to handle it, and things break

Yes plugin site could be made more robust, but i don't want to work around bad data. We've done it so much in the past and thats how we have the mess/tech debt we do now.

**Comment by halkeye** [comment]
With https://github.com/jenkinsci/autonomiq-plugin/pull/11 being filed I'm closing this ticket.
