### ISSUE TITLE
Two day old release of schedule-build plugin is not visible on plugins site

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#830]
@DarinPope and I released the 1.0.0 version of the schedule-build plugin on Thursday as part of our live stream on modernizing Jenkins plugins.  The release is visible in the update center and on the [Jenkins mirror list](https://get.jenkins.io/plugins/schedule-build/1.0.0/schedule-build.hpi?mirrorlist), but the release is not visible on the plugins site.

The [schedule-build plugin page on the plugins site](https://plugins.jenkins.io/schedule-build/) looks like this to me:

![screencapture-plugins-jenkins-io-schedule-build-2021-10-23-08_58_00-edit](https://user-images.githubusercontent.com/156685/138561538-987bb9b8-be35-4f7b-97a6-8148b35d80b3.png)

**Comment by halkeye** [comment]
The last build date on the bottom of the page is 2021-10-21T18:03:23.000Z so that means something is wrong

**Comment by MarkEWaite** [comment]
Thanks!  I should have checked the last build date.

**Comment by halkeye** [comment]
Looks like the css its importing from jenkins.io isn't valid?

```
/home/jenkins/agent/workspace/plugin-site_master/src/layout.jsx: Unexpected token, expected "}" (13:11)

  11 |           
  12 |   i.icon-report::before {
> 13 |     content: "\f071";
     |            ^
  14 |     color: #FFA91B;
  15 |     font-family: FontAwesome !important;
  16 |     font-size: 20px;
```

**Comment by halkeye** [comment]
oh someone injected raw css into the layout, script didn't handle that. should be easy to fix

**Comment by halkeye** [comment]
![image](https://user-images.githubusercontent.com/110087/138564927-50beef6f-78ba-465a-9b15-6be72d3c109d.png)
that is not valliddddd

**Comment by halkeye** [comment]
okay all updated and fixed now :)
