### ISSUE TITLE
Plugin pages - "Open issues" link shows issues that are Closed

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#853]
[Plugin](https://plugins.jenkins.io) pages like https://plugins.jenkins.io/git-client/ include helpful links to "Report an issue" and "Open issues".  The "Open issues" link opens a Jira query that also includes issues that are closed. 

Could the "Open issues" link be extended to exclude issues that are closed?

## Screenshots 

![screencapture-plugins-jenkins-io-git-client-2021-11-28-06_34_51-edit](https://user-images.githubusercontent.com/156685/143770113-f1fcb387-286e-42da-8bb3-73f8f999275d.png)

## Possible Solution 

Change the link from https://issues.jenkins.io/issues/?jql=component=17423 to https://issues.jenkins.io/issues/?jql=component%3D17423%20and%20status!%3DClosed

Several different Jira workflows are used by Jenkins plugins.  Some do not use `Closed` as the final state.  Even with that, I believe that requesting `status!=Closed` is a safe enhancement to the "Open issues" link.

**Comment by timja** [comment]
Generally ‘resolution is empty’ is a safe query for Jenkins plugins

**Comment by daniel-beck** [comment]
This is just a bad link label, RPU metadata does not specify whether it's only open issues.

A problem with pre-filtering can be that a user is on an old release but experiences a bug that was resolved recently; not finding anything, a duplicate issue is filed.

Ideally Jira would have an easy "all / open only" switch like GitHub, but I don't think it allows that.

**Comment by halkeye** [comment]
I have a branch i'll try and get merged that cleans up the issue tab a bunch, and supports both jira and github. Wouldn't be that hard to add open/closed to that, assuming I didn't already do it. I'll try and get it deployed this week.

**Comment by zbynek** [comment]
The reason I changed the query and not the label is that 
1) the open issues are in most cases more relevant 
2) for plugins with GitHub issues the link only shows open issues

But we could also show all issues with unresolved on top (add `ORDER BY resolution DESC` to jql) and change the link from "Open issues" to just "Issues".

I still don't see the point of maintaining the issues tab, but if that's the plan, we can also just remove the issue link from the sidebar.

**Comment by halkeye** [comment]
its easy enough to add the resolution to the plugin site, its hard to take away resolution from RPU data. I'd rather it get done on plugin site/presentation layer.

**Comment by daniel-beck** [comment]
> But we could also show all issues with unresolved on top (add `ORDER BY resolution DESC` to jql) and change the link from "Open issues" to just "Issues".

This might work, or perhaps `order by status ASC` 👍
