### ISSUE TITLE
Menu is broken when opening anchor links

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#885]
Clicking "dependencies" on https://plugins.jenkins.io/matrix-auth/ changes the URL to https://plugins.jenkins.io/matrix-auth/#dependencies.

Opening a link to "https://plugins.jenkins.io/matrix-auth/#dependencies" takes you there directly, but the menu doesn't change accordingly:

> <img width="675" alt="Screenshot 2021-12-06 at 14 55 17" src="https://user-images.githubusercontent.com/1831569/144858335-33aa6da2-49df-45a5-903e-374dc9d1e46f.png">

**Comment by halkeye** [comment]
Do you see anything in your console or anything? I just tried it and things seem to work right for me.

![Animation](https://user-images.githubusercontent.com/110087/144891307-30df5858-cb95-4153-83fa-2f4bb3eb6f43.gif)

The tabs are pure javascript so its surprising it works in some case and some other places. if its still happening, which browser/etc combo?

**Comment by daniel-beck** [comment]
The important part is opening the link in a new tab. That's the whole point of it being a separate URL, no? That one can link to a tab from elsewhere?


https://user-images.githubusercontent.com/1831569/144904999-55e47a43-e6ba-421f-a14c-752c65f249a2.mov

**Comment by halkeye** [comment]
Oh oh. Okay. So it's not that the functionality doesn't work, it's that the
ui doesn't update on new tab.

My guess is its the new header linking support. I'll take a look

**Comment by halkeye** [comment]
Had to revert. I liked the new solution, but it caused rendering issues.
