### ISSUE TITLE
Table of contents links broken in adoc pages on plugins site

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-site#887]
Plugins that use adoc format and embed a computed table of contents (like the [git plugin](https://plugins.jenkins.io/git/)) no longer resolve internal links to sections of the document when clicking the entries in the table of contents.

For example, the ["Enabling JGit" link](https://plugins.jenkins.io/git/#enabling-jgit) in the table of contents using the `enabling-jgit` id, but the id on the section heading is actually `plugin-content-enabling-jgit`.

The links worked previously but don't work any longer.  The docs can be converted to markdown if needed, but adoc was easier for table of contents initially.

**Comment by halkeye** [comment]
~github render uses a different prefix than I used, it should be easy to switch gatsby-node.js to user-conent~

re-reading what you wrote, github HTML does user-content-$id, I chose to do plugin-content-$id on plugin site, and it looks like your just doing $id

I'm reluctant to drop the prefix, but it's probably fine. Lets thing about it for a bit

**Comment by halkeye** [comment]
another idea, rehype provides toc data, wonder if its worth trying to figure out some markup that could have toc on any page with more than X headers, maybe floating to the right or something.
