### ISSUE TITLE
Plugins Releases page - Github PR links no longer redirect

### ISSUE THREAD

**Issue by wwuck** [jenkins-infra/plugin-site#894]
Problem with the [Plugins Index](https://plugins.jenkins.io) Releases page.

Github PR links on plugin Releases tab are no longer redirecting to the PR.

Eg. https://plugins.jenkins.io/email-ext/#releases latest release 2.86 has a link to `https://github.com/jenkinsci/email-ext-plugin/issues/332`.  This previously redirected automatically to `https://github.com/jenkinsci/email-ext-plugin/pull/332` but now no longer redirects and just returns HTTP 404.

I have seen a similar bug report for Renovate Bot at https://github.com/renovatebot/renovate/issues/13038.

**Comment by halkeye** [comment]
oh thats interesting...

**Comment by halkeye** [comment]
normally issues/# will redirect to pull if need be, but because email-ext has issues disabled, it gets a 404. This will be interesting to figure out a solution for.

**Comment by wwuck** [comment]
It doesn't appear to be related to issues enable/disabled.

I can see the problem also on https://plugins.jenkins.io/code-coverage-api/#releases which has issues enabled in Github.

**Comment by halkeye** [comment]
huh. your right. I made the assumption because it used to work.

**Comment by timja** [comment]
Pretty sure this is a bug on the GitHub side, e.g see this changelog: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v2.89.0

none of the links work on it

**Comment by KalleOlaviNiemitalo** [comment]
It has been reported at <https://github.com/github/feedback/discussions/8623>.

**Comment by timja** [comment]
GitHub rolled back their change, tested and it works again
