### ISSUE TITLE
Incorrectly sorted releases

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/plugin-site#914]
https://plugins.jenkins.io/workflow-cps-global-lib/#releases currently lists 544.vff04fa68714d above 545.v7b28cce323cf even though it is older. Please make sure you are using Maven's version parser, https://github.com/jenkinsci/lib-version-number, or something compatible.

**Comment by daniel-beck** [comment]
You pull in GitHub release descriptions if they exist, perhaps you could use their ordering as well? Still different from what's requested here in case of backports, but perhaps even better than this requests?

Alternatively we can probably change `plugin-versions.json` to have a better timestamp?

**Comment by halkeye** [comment]
> You pull in GitHub release descriptions if they exist, perhaps you could use their ordering as well?

I could, but right now I've been using them as runtime improvements and not any sort of actual data source.

![image](https://user-images.githubusercontent.com/110087/146632032-e2b3e811-0cee-4a46-bba2-f55011889916.png)

that sorting looks correct? I'll clean it up and try and get it merged tomorrow

**Comment by halkeye** [comment]
🤦 buildDate was being treated as a string for sorting purposes. I know how to fix it.

I think ordering by builddate is still the right answer, but I can use version if that's recommended.

**Comment by daniel-beck** [comment]
The two versions mentioned in the issue have the same `buildDate`, so would sort the same.
