### ISSUE TITLE
Changelog markdown is rendered inconsistently with GitHub

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site#957]
Compare:

https://github.com/jenkinsci/matrix-auth-plugin/releases/tag/matrix-auth-3.0

> <img width="2351" alt="Screenshot 2021-12-28 at 10 25 23" src="https://user-images.githubusercontent.com/1831569/147551177-ff64e7a5-fb07-49df-98f1-713e3b543c5f.png">

https://plugins.jenkins.io/matrix-auth/#releases

> <img width="1141" alt="Screenshot 2021-12-28 at 10 25 42" src="https://user-images.githubusercontent.com/1831569/147551313-9151887d-3790-4158-9fd4-8abd5caed9a5.png">

The intentional line breaks are missing on the plugin site, perhaps indicating a non-GH flavored Markdown renderer? Instead, we don't even get a space after sentence ending periods.

**Comment by halkeye** [comment]
I want to reply saying I saw the issue. This is on my immediate radar for trying to shut down plugin-site-api, but it probably won't be before next week. Soon everything will use the same renderer.

**Comment by halkeye** [comment]
![image](https://user-images.githubusercontent.com/110087/163687380-52a3586e-a9ce-4091-b296-441fec8475f9.png)

Looks good to me. @daniel-beck reopen if you think it needs it
